BabylonJS/BabylonNative

- Library/CMakeLists.txt
- Library/Source/NativeEngine.cpp
- Revert the caching change in Babylon.js
- Update bgfx with max 32 streams fix (attempt 2)
> Fix for uniform caching and bgfx with max 32 streams

- CMakeLists.txt
- azure-pipelines.yml
macosx CI
CMake special flag for macosx (took me a while to find that one)
> azure pipelines jobified/macosx CI

- Library/Source/NativeEngine.cpp
rgb,rgba, bgra supported formats for PoT textures
Need more formats/NPoT?
tested with Sponza, FlightHelmet and RenderDoc
> mipmap generation for PoT textures

- Library/Dependencies/napi/include/napi/napi-inl.h
- Library/Dependencies/napi/source/env_chakra.cc
- Library/Dependencies/napi/source/js_native_api_chakra.cc
- Library/Dependencies/napi/source/js_native_api_chakra.h
- Library/Source/NativeEngine.cpp
- Fixed all TODOs and HACKs with the exception of the fatal error one.
- Implemented missing functionality (hasOwnProperty, dataViews, etc.)
- Remove dead code
- Reorder to match v8 implementation
- Add argument checks to match v8 implementation
> Clean up Chakra implemention of N-API

- Library/Source/NativeEngine.cpp
- Library/Source/NativeEngine.h
- Library/Source/NativeXr.cpp
Will regenerate babylon.max.js once https://github.com/BabylonJS/Babylon.js/pull/7056 is merged
> clear flags and values

- Library/Source/NativeEngine.cpp
I missed that when addressing feedback
> memcpy instead of byte copy

- Library/Include/Babylon/RuntimeAndroid.h
- Library/Include/Babylon/RuntimeApple.h
- Library/Include/Babylon/RuntimeUWP.h
- Library/Include/Babylon/RuntimeWin32.h
- Library/Source/NativeEngine.cpp
- Library/Source/NativeEngine.h
- Library/Source/RuntimeAndroid.cpp
- Library/Source/RuntimeApple.cpp
- Library/Source/RuntimeImpl.cpp
- Library/Source/RuntimeImpl.h
- Library/Source/RuntimeUWP.cpp
- Library/Source/RuntimeWin32.cpp
- TestApp/Source/Android/app/src/main/cpp/BabylonNativeJNI.cpp
- TestApp/Source/UWP/App.cpp
- TestApp/Source/Win32/App.cpp
- TestApp/Source/iOS/LibNativeBridge.h
- TestApp/Source/iOS/LibNativeBridge.mm
- TestApp/Source/iOS/ViewController.swift
- TestApp/Source/macOS/ViewController.mm
thread init and run split in 2 functions.
It's not possible to hook a MetalLayer in a thread other than the main thread.
> Device context in main thread

- Library/Source/NativeXr.cpp
V8 does not support persisting strings
> Don't use Napi::Persistent with Napi::String

- Apps/Playground/iOS/ViewController.swift
- Dependencies/napi/source/js_native_api_JavaScriptCore.cc
- Plugins/NativeEngine/Source/NativeEngine.cpp
- Plugins/NativeEngine/Source/ShaderCompilerMetal.cpp
- improved JSC (properties, exceptions that get display in Safari, arraybuffer)
- Correct binding of textures for metal
- fixed view size in ios viewcontroller
> update to get marble tower running on mac and ios

- Documentation/AndroidSimulator.md
Changes from Ryan. Copy/pasted from readme to a separate file.
@syntheticmagus Can you add a link from the read to this file in the Android section. As well as the DebugJavascriptMacIOS.md in the mac/ios section?
> Android Simulator Doc

- Apps/ValidationTests/Scripts/marble.js
Handy scene to test.
Tested successfully (with env map) on Win32, Android, MacOS and iOS
> Marble tower in validation tests

- Dependencies/BabylonNativeUtils/Source/NetworkUtils.cpp
- Plugins/NativeEngine/Source/InitializeNativeEngine.cpp
- Plugins/NativeEngine/Source/NativeEngine.cpp
> fix regressions on Android

- Core/JsRuntime/CMakeLists.txt
- Core/JsRuntime/Include/Babylon/JsRuntimeScheduler.h
- Dependencies/BabylonNativeUtils/Source/NetworkUtils.cpp
- Plugins/XMLHttpRequest/Source/XMLHttpRequest.cpp
- Plugins/XMLHttpRequest/Source/XMLHttpRequest.h
- Plugins/XMLHttpRequest/Source/XMLHttpRequestUWP.cpp
The XMLHttpRequest class was broken for UWP when accessing local files. This fixes it.
> Fixes for XMLHttpRequest on UWP

- Plugins/NativeEngine/Source/NativeEngine.cpp
- bgfx + bgfx.cmake updated to the latest master version
- discard states for faster uniforms settings
- tested with marbletower and "3000boxes" snippet
> update bgfx + submit discard

- Apps/Playground/iOS/Base.lproj/LaunchScreen.storyboard
- Apps/Playground/iOS/Base.lproj/Main.storyboard
- Apps/Playground/iOS/ViewController.swift
- Plugins/NativeEngine/Source/NativeEngine.h
closes #241 
Partial fix, I still get issues with wrong dimensions reported. But the crash is fixed for now. I also changed the storyboard to work with any screen resolutions.
> Fix for ios resize + universal storyboard

- README.md
- azure-pipelines.yml
- GCC 9 compilation pipeline for Linux (doesn't build with GCC8 because of a template issue with ScriptLoader::impl)
- Readme updated to reflect the change
> gcc pipeline Linux

- Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp
fixes #280 until we do it properly with glslang.
> support for array uniform opengl

- Apps/ValidationTests/Scripts/config.json
- Plugins/NativeEngine/Source/BgfxCallback.cpp
- Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp
- azure-pipelines.yml
Validationt tests on Linux (JSC + OpenGL) with results artifact publishing.
> Validation tests Linux CI

- Plugins/NativeEngine/Source/ResourceLimits.cpp
- Plugins/NativeEngine/Source/ShaderCompiler.cpp
- Plugins/NativeEngine/Source/ShaderCompilerD3D.cpp
- Plugins/NativeEngine/Source/ShaderCompilerMetal.cpp
- Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp
- Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp
- Plugins/NativeXr/Source/NativeXr.cpp
- azure-pipelines.yml
Release build for Android and Apple on CI and update glslang because the unused variable has been fixed.
> Release build on CI for Android and Apple

- Dependencies/napi/napi-jsi/include/napi/napi-inl.h
Also implement FunctionReference more
> Fix Napi::Value copy constructor for empty Napi::Value

- Plugins/NativeEngine/Source/NativeEngine.cpp
- Plugins/NativeEngine/Source/NativeEngine.h
- Plugins/NativeEngine/Source/ShaderCompilerD3D.cpp
- Fix hlsl compatibility with point rendering
- bindbuffer function
- bjs max update
fixes https://github.com/BabylonJS/BabylonNative/issues/347
This PR contains built changes from bjs : https://github.com/BabylonJS/Babylon.js/pull/8650
> point cloud rendering

- Plugins/NativeEngine/Source/NativeEngine.cpp
fixes https://github.com/BabylonJS/BabylonNative/issues/368
bjs update with commit https://github.com/BabylonJS/Babylon.js/pull/8967/commits/cab5feeee5a04ff74fb9d017502aa344f282bcf5
> depth tests parameters

- Plugins/NativeEngine/Source/NativeEngine.cpp
- Plugins/NativeEngine/Source/NativeEngine.h
> index start/count for drawcalls

- .github/workflows/nightly.yml
- Apps/ValidationTests/Shared/TestUtils.h
- Apps/ValidationTests/Win32/App.cpp
revert back to use WN_DESTROY
upload artifact from night build
> WM_DESTROY and nightly artifacts

- azure-pipelines.yml
We will turn it back on once we figure out what is causing the instability.
> Turn off Ubuntu CI for now

- Dependencies/xr/Source/OpenXR/XR.cpp
We had some tabs sneak their way into a recent change.
> Convert tabs to spaces in OpenXR/XR.cpp

- Apps/ValidationTests/macOS/ViewController.mm
- Dependencies/UrlLib/Source/Apple/UrlRequest.mm
- fix URL containing forbiden characters
- bool RENDER_ON_JS_THREAD on macOS validationtests
> small fixes for macos

- Apps/ValidationTests/Scripts/config.json
- Plugins/NativeEngine/Source/NativeEngine.cpp
- Plugins/NativeEngine/Source/NativeEngine.h
bjs with commit https://github.com/BabylonJS/Babylon.js/pull/9747/commits/cfdf8b30b4c5da7af798f78a27ca84348c98fc56
new issue related to the test scene needing 2 rendered frames instead of 1 : https://github.com/BabylonJS/BabylonNative/issues/559
1 validation test scene added
> point light shadows

- Plugins/NativeEngine/Source/NativeEngine.cpp
fixes #556 
Converts R8 textures to RGB8 using bimg conversion function
> converts R8 to RGB8 textures

- Plugins/NativeEngine/Source/NativeEngine.cpp
fixes #585 
babylon.max.js with commit https://github.com/BabylonJS/Babylon.js/pull/9866/commits/c4d3e3f4a78876eb0a4dbf1939cc7eaf63b1698b
> use front facing infos from bjs

- Plugins/NativeXr/Source/NativeXr.cpp
The new webXR API update renamed the joints and changed how they are accessed, which changes how we pass joint data to babylon.JS.
https://immersive-web.github.io/webxr-hand-input/#xrhand-interface
> Updating hands for new webXR API

- Dependencies/napi/napi-jsi/include/napi/napi-inl.h
> Add missing Get function in napi-jsi

- Apps/Playground/CMakeLists.txt
- Apps/ValidationTests/CMakeLists.txt
- Plugins/NativeEngine/Source/NativeEngine.cpp
This reverts commit 9fa1a84f5f5a67e5ad7a0a9c92eab031cc85b6e4.
> Revert "add all_load flag for apple targets (#632)"

- .github/CODEOWNERS
Try using code owners for #599
> Add code owners for BabylonScripts

- azure-pipelines.yml
Android build broke when Ubuntu image was updated to cmake 3.20. This change forces the cmake version.
> Install specific version of CMake on Android Unbuntu

- Apps/ValidationTests/CMakeLists.txt
- Apps/ValidationTests/Win32/App.cpp
> XR Initialization for ValidationTests

- Apps/Playground/CMakeLists.txt
- Apps/ValidationTests/CMakeLists.txt
- Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm
And add a check for TextureCache deallocation in NativeCamera
> Clean CMake for Apple Apps

- .github/workflows/nightly.yml
VT folders are created in CMake, I changed the jobs but forgot about the nightly...until I was prompted to fix it.
> VT folders creation done in CMake

- Apps/Playground/Scripts/experience.js
- Dependencies/xr/Source/OpenXR/XR.cpp
- Plugins/NativeXr/Source/NativeXr.cpp
Creates OpenXR binding for inputs for both controllers separately
Closes #766
> Multipointer input bindings

- Apps/package-lock.json
- Apps/package.json
> Update to bjs npm packges 5.0.0-alpha.30

- Polyfills/Canvas/CMakeLists.txt
- Polyfills/Canvas/Source/Canvas.cpp
- Polyfills/Canvas/Source/Image.cpp
- Polyfills/Canvas/Source/Image.h
Native Canvas Image object Stub.
For canvas drawImage method / GUI Image.
Splitting PRs for ease of review.
JS Abstraction PR is here : https://github.com/BabylonJS/Babylon.js/pull/10709
> Stub for Native Canvas Image

- Dependencies/xr/Source/ARKit/XR.mm
> Correct state management for iOS XR frame buffer

- Dependencies/napi/napi-jsi/include/napi/napi-inl.h
> NAPI-JSI: Actually return the result in static class method

- Polyfills/Canvas/Source/Context.cpp
This PR improves the argument parsing when setting the font for Canvas based text rendering to allow setting font size as well as font family name.  Instead of just assuming that the passed in argument for font only contains a font family name, we split the font options as a space delimited list of options, and parse each argument separately.   We maintain the same default font size of 16 when the argument is unspecified or invalid.  In the future we should likely also include support specifying for font styles as well.
For example specifying the font:
"72px droidsans" will match to a font size of 72 pixels and the font name "droidsans".
Below are some example screenshots of rendering at different font sizes in the playground.
12 px:
24 px:
36 px:
> Allow specifying font size for fonts in Canvas Context Polyfill

- Dependencies/napi/napi-direct/source/js_native_api_javascriptcore.cc
Fixes #880
This change fixes a problem where exceptions that are thrown from a native NAPI constructor/function are fired in the wrong context which makes them uncatchable.
> Fix napi jsc exception handling

- Apps/package-lock.json
- Apps/package.json
Brings in fix for texture cache
> Update to Babylon.js 5.0.0-alpha.47

- Dependencies/UrlLib/Source/Android/UrlRequest.cpp
Fixes loading files from URLs on Android. Load from the full URL string rather than just the path.
> Fix Android URL Requests

- Polyfills/Canvas/Source/Context.cpp
- Polyfills/Canvas/Source/Context.h
missing getter for canvas context font.
> fix nightly / canvas

- Apps/ValidationTests/Scripts/gltf2_asset_generator_test.js
- Apps/ValidationTests/Scripts/gltf2_sample_models_test.js
> GLTF2 removed tests and changed path

- Plugins/NativeXr/Source/NativeXr.cpp
Planes and meshes should be using XRSpace instead of XRReferenceSpace. I'm also storing the space references as properties rather than exposing them as accessors for improved performance on the JS side.
> Use XRSpaces with planes and meshes

- Core/Graphics/CMakeLists.txt
- Plugins/NativeEngine/CMakeLists.txt
> Fix broken #define for graphics API

- Dependencies/xr/Source/ARKit/XR.mm
This reverts commit ba16bcce0950fa036bd58d2942481a0df6cb346b.
This change is causing a crash on iOS but, strangely, only when the debugger is not present. Reverting for now to prevent the crash, but this will also reintroduce #932 that was fixed by the reverted change.
> Revert "Ensure textures are made purgeable only after the command buffer completes (#965)"

- Dependencies/napi/napi-direct/source/js_native_api_chakra.cc
- Polyfills/Canvas/Source/Context.cpp
- Polyfills/Canvas/Source/Context.h
@bghgary feel free to change the 'fix' for the crash in debug with empty strings.
> Small fixes for demo

- Polyfills/Canvas/Source/Context.cpp
- Polyfills/Canvas/Source/Context.h
- Polyfills/Canvas/Source/MeasureText.cpp
- Polyfills/Canvas/Source/MeasureText.h
- Global Alpha
- Clipping
- Text measurement
- Clear rect blending
> Canvas Fix for demo

- Documentation/faq.md
Get callstacks and other infos from Android device.
> faq android

- Documentation/AppRuntime.md
"Thought" should be "Though". This change fixes it.
> Fix spelling in Documentation/AppRuntime.md

- Dependencies/UrlLib/Include/UrlLib/UrlLib.h
- Dependencies/UrlLib/Source/Android/UrlRequest.cpp
- Dependencies/UrlLib/Source/Apple/UrlRequest.mm
- Dependencies/UrlLib/Source/Shared/UrlRequest.h
- Dependencies/UrlLib/Source/Unix/UrlRequest.cpp
- Dependencies/UrlLib/Source/Windows/UrlRequest.cpp
- Plugins/NativeCapture/Source/NativeCapture.cpp
- Plugins/NativeEngine/Source/NativeDataStream.h
- Plugins/NativeXr/Source/NativeXr.cpp
Doing this because I need something from the new CMakeLists.txt in GSL 4, but it's good to update anyways.
> Update to latest arcana with GSL 4

- Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp
- Apps/Playground/Android/app/src/main/java/BabylonNative/BabylonView.java
- Apps/Playground/Android/app/src/main/java/BabylonNative/Wrapper.java
- Apps/Playground/UWP/App.cpp
- Apps/Playground/UWP/App.h
- Apps/Playground/Win32/App.cpp
- Apps/Playground/X11/App.cpp
- Apps/Playground/iOS/LibNativeBridge.h
- Apps/Playground/iOS/LibNativeBridge.mm
- Apps/Playground/iOS/ViewController.swift
- Apps/Playground/macOS/ViewController.mm
- Plugins/NativeInput/Include/Babylon/Plugins/NativeInput.h
- Plugins/NativeInput/Source/Shared/NativeInput.cpp
- Plugins/NativeInput/Source/Shared/NativeInput.h
PR for Improved Pointer Support.  This PR adds supports for additional mouse buttons and the mouse wheel for Mouse implementations and multi-touch support for touch inputs.
> Improve Pointer Support

- Plugins/NativeEngine/Source/NativeEngine.cpp
> Fix bad warning message when creating frame buffer

- Plugins/NativeEngine/Source/ShaderCompilerCommon.cpp
- Plugins/NativeEngine/Source/ShaderCompilerCommon.h
that broke morph targets
See https://github.com/bkaradzic/bgfx/pull/2885#discussion_r991464619
> Fix breaking change from bgfx update

- Dependencies/napi/napi-direct/source/js_native_api_javascriptcore.cc
There is a problem with the current implementation where calling `instanceof` for an object constructed from a NAPI object when targeting JSC. Suppose `Foo` is a class exposed using `Napi::ObjectWrap`, here is an example:
```javascript
var foo = new Foo();
console.log(foo instanceof Foo);
```
This was incorrectly loggin `false`. It will now correctly log `true`. Thanks to @CoPrez for finding the solution! 👍
> FIx constructor prototype chain for JSC in NAPI

- .github/jobs/win32.yml
- Apps/ValidationTests/Scripts/config.json
- Apps/ValidationTests/Scripts/validation_native.js
- Apps/package-lock.json
- Apps/package.json
- update PG versions for missing methods (in sync with bjs config.json)
- Validation test display a message when no pixel difference
- Update Babylon.js
fixes #1162
> Validation tests maintenance

- Apps/package-lock.json
- Apps/package.json
This PR contains an update to the Babylon.js NPM package to 5.53.1
> Update BJS to 5.53.1

- Apps/UnitTests/Scripts/tests.js
related https://github.com/BabylonJS/JsRuntimeHost/pull/40
> Mocha Premade reporter

- CMakeLists.txt
- Install/Install.cmake
Fix v8 without inspector installation
also needs this https://github.com/BabylonJS/JsRuntimeHost/pull/46
> v8 without inspector

- Apps/Playground/CMakeLists.txt
- Plugins/ExternalTexture/Source/ExternalTexture_Base.h
- Plugins/ExternalTexture/Source/ExternalTexture_Metal.mm
Also add external texture plugin to Playground app so that it is at least built
> Fix external texture for metal

- CMakeLists.txt
Updated glslang version to get fixes for Linux when using latest GCC.
> Updated glslang commit to get fix for linux

- Core/Graphics/Source/DeviceImpl.cpp
Added a quick fix for threading affinity macro.
> Fixed issue with threading macros

- Polyfills/Canvas/Source/Canvas.cpp
- Polyfills/Canvas/Source/Canvas.h
Fix for remove call : https://github.com/BabylonJS/Babylon.js/commit/68a63f3012ac86fe80f0b044dc85f2bc22d79fd8
> Add Method to remove canvas from document

- Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp
- Apps/Playground/iOS/LibNativeBridge.mm
> Fix shadowed variables for XR

- Core/Graphics/Include/RendererType/D3D11/Babylon/Graphics/RendererType.h
- Core/Graphics/Include/RendererType/D3D12/Babylon/Graphics/RendererType.h
- Core/Graphics/Include/RendererType/Metal/Babylon/Graphics/RendererType.h
- Core/Graphics/Include/RendererType/OpenGL/Babylon/Graphics/RendererType.h
- Core/Graphics/Include/Shared/Babylon/Graphics/Device.h
- Core/Graphics/Source/DeviceImpl.cpp
- Core/Graphics/Source/DeviceImpl_D3D11.cpp
- Core/Graphics/Source/DeviceImpl_D3D12.cpp
- Core/Graphics/Source/DeviceImpl_Metal.cpp
- Core/Graphics/Source/DeviceImpl_OpenGL.cpp
> Expose Metal command queue for Apple platforms

- .github/jobs/android.yml
- .github/jobs/cmake.yml
- Apps/Playground/Android/app/build.gradle
- Apps/Playground/Android/app/src/main/AndroidManifest.xml
- Apps/Playground/Android/build.gradle
- Apps/Playground/Android/gradle/wrapper/gradle-wrapper.properties
- Apps/UnitTests/Android/app/build.gradle
- Dependencies/CMakeLists.txt
Should fix a bunch of issues that start appearing with newer Android Studio
and
```
Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module
```
> gradle version update

- Install/Install.cmake
Changes from #1325 caused the install files to have extra files. This is a simpler way to do it.
> Fix cmake install target

- CMakeLists.txt
> Update to latest JsRuntimeHost with exposed napi_add_finalizer

- CMakeLists.txt
- Dependencies/CMakeLists.txt
Brings in fix for napi_add_finalizer for JSC
> Update JsRuntimeHost to latest

- Apps/Playground/iOS/ViewController.swift
Hey, 
This PR cleans up view controller in iOS playground from explicit unwraps. It should give a better example of how people can use BabylonNative in their projects
> fix: cleanup view controller

- Plugins/NativeEngine/Source/NativeEngine.cpp
Temporary fix for a user until this is done and replaces this change: https://github.com/BabylonJS/BabylonNative/issues/1392
> R16 Texture format support (temporary fix)

- Plugins/NativeOptimizations/Source/NativeOptimizations.cpp
This is the counterpart to https://github.com/BabylonJS/Babylon.js/pull/15234. Putting these two together will improve the performance of `refreshBoundingInfo` function dramatically.
> Add apply skeleton function to native optimizations plugin

- Polyfills/Canvas/Source/Context.cpp
Small fixes after testing this PG : https://playground.babylonjs.com/#UZRZXU
> Canvas Context angle/fontsize fixes

- Apps/Playground/Scripts/experience.js
- Polyfills/Canvas/Source/Context.cpp
- Polyfills/Canvas/Source/Context.h
Adds implementation for canvas `transform` function https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/transform
> Canvas transform implementation

- Apps/Playground/Scripts/experience.js
- Polyfills/Canvas/Source/Context.cpp
- Polyfills/Canvas/Source/Context.h
- Polyfills/Canvas/Source/LineCaps.h
- `lineCap` https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap
- `lineJoin` https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin
- `miterLimit` https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/miterLimit
> Add lineCap, lineJoin, miterLimit

- Apps/Playground/Scripts/experience.js
- Polyfills/Canvas/CMakeLists.txt
- Polyfills/Canvas/Source/Canvas.cpp
- Polyfills/Canvas/Source/Context.cpp
- Polyfills/Canvas/Source/Context.h
- Polyfills/Canvas/Source/Gradient.cpp
- Polyfills/Canvas/Source/Gradient.h
Gradient / color stop glue code and small example.
> Gradient color stop

- Apps/package-lock.json
- Apps/package.json
Updated Babylon.js package to 8.0
> Update Babylon.js version

- azure-pipelines.yml
> Up CMake/ Xcode versions

- BUILDING.md
Followup https://forum.babylonjs.com/t/could-not-get-babylon-native-android-build-working/58534/2
> Removed confusing sentence

- CMakeLists.txt
Updated JsRuntimeHost with proper exception header include.
> Updated JsRuntimeHost

- Apps/Playground/Android/app/src/main/AndroidManifest.xml
- Apps/Playground/Android/app/src/main/res/xml/network_security_config.xml
- Apps/package-lock.json
- Apps/package.json
local http needs a new manifest. Also bump bjs version
> update Android manifest
