BabylonJS/BabylonNative

.clang-format

.clang-format stub. 
bootstrapped from https://github.com/Microsoft/cpprestsdk/blob/master/.clang-format
3 possibilities:
- set VS to use it. It formats the code as you type.
- add a target in CMake to use clang-format
- make a ps script to format files
A good practice would be to do a clang format pass once your PR is approved and not spend time tracking poorly placed braces, missing spaces ,... during PR reviews
What's your take on that?

clang format script

---

Library/Source/NativeEngine.cpp
Library/Source/NativeEngine.h
Library/Source/NativeWindow.cpp
Library/Source/NativeWindow.h
Library/Source/RuntimeImpl.cpp

Fixed usage of NAPI contract so that it works in V8, which is a little more restrictive on this than Chakra.
Over-the-shoulder reviewed by @bghgary

Fixed usage of NAPI contract so that it works in V8

---

Library/Dependencies/napi/source/js_native_api_JavaScriptCore.cc
Library/Source/NativeEngine.cpp
Library/Source/NativeEngine.h
TestApp/Scripts/experience.js
TestApp/ValidationTests/decode_encode_image_test.js

I noticed BABYLON.Tools.LoadFile yesterday and wanted to try it for validation image loading.
It's simpler to use than what I started in my validation branch. The idea is to change NativeCanvas capture to return an Image instead of a uint8array. Compare images and write the captured image if a difference is detected.

Image decoding/encoding

---

Library/Source/NativeEngine.cpp
Library/Source/NativeEngine.h
Library/Source/NativeXr.cpp

Quick workaround to get XR working in master. Note that this is a temporary fix, intended to be undone once the reworked architecture for working with `ViewID`s is finished.

Xr workaround

---

TestApp/Source/UWP/App.cpp
TestApp/Source/UWP/App.h

Fixed UWP so that pressing "R" correctly sets the backbuffer size after recreating the runtime.

Fix UWP refresh render size

---

Library/CMakeLists.txt
Library/Source/NativeEngine.cpp
Library/Source/ShaderCompiler.cpp
Library/Source/ShaderCompiler.h
Library/Source/ShaderCompilerD3D.cpp
Library/Source/ShaderCompilerMetal.cpp

Use syntax tree from glslang instead of a string replace to invert dFdy operand.

Fix hack for inverting dFdy

---

Library/Dependencies/xr/Include/XR.h
Library/Dependencies/xr/Source/Windows/XrPlatform.h
Library/Dependencies/xr/Source/XR.cpp
Library/Source/NativeXr.cpp
TestApp/Scripts/experience.js

So here's a weird thing. After talking with @sebavan and fiddling with the color spaces a bit, we found that if we lie to the OpenXR runtime about the color space of the swapchain it's receiving, we can get the rendering output we expect from the latest runtimes---neither too dark nor too light. I'm pretty sure this isn't something we want to be in the business of doing long-term, and maybe not even short-term, but I thought this draft PR might be a good place to discuss it and figure out where we want to go from here.

Windows Mixed Reality color space workaround

---

Library/Include/Babylon/Runtime.h
Library/Source/NativeEngine.cpp
Library/Source/NativeWindow.cpp
Library/Source/Runtime.cpp
Library/Source/RuntimeImpl.cpp
Library/Source/RuntimeImpl.h
Library/Source/RuntimeUWP.cpp
Library/Source/RuntimeWin32.cpp
TestApp/Source/Shared/InputManager.h

Fixes #63 
* Rename `Execute` to `Dispatch`
* Remove `Env`
* Update `LoadScript` to be more parallel
We had a discussion about changing the contract more, but after trying to implement it, I think this is the right contract. We had originally thought there was an ordering issue with LoadScript, but I've confirmed that it works as intended (calling runtime methods guarantees order of execution on the JavaScript thread). It should be perhaps documented better than it is currently written.

Runtime contract updates

---

Library/Source/NativeEngine.cpp
Library/Source/NativeEngine.h
README.md

bgfx update introduces vertexDecl to be replaced by vertexLayout
bgfx.cmake PRs that need to be merged at the same time
https://github.com/BabylonJS/bgfx.cmake/pull/2
upstream PR:
https://github.com/JoshuaBrookover/bgfx.cmake/pull/64
Not sure it will be merged quickly in upstream so I did one on our own bgfx.cmake repo.

bgfx vertex decl replaced by vertex layout

---

TestApp/Source/UWP/App.cpp
TestApp/Source/UWP/App.h

Fix issue for https://github.com/BabylonJS/BabylonNative/issues/103
Added resume call or application hangs when restored from minimized state.
Do you know how to disable background drawing? Window flashes blue when resizing.

Handle screen scale

---

Library/Source/RuntimeImpl.cpp
Library/Source/RuntimeImpl.h

I need to flush rendering commands and be sure that no draw call is being performed when I suspend the app.
No need for this with d3d11.
On Android, the surface is destroyed when the app is in background. Any drawcall will crash the app or put it in unstable state.
On Mac, I also have to do it when resizing the window (disable rendering->let UI Kit resize the window ->enable rendering)

mutex for flushing rendering commands

---

Library/Source/NativeEngine.cpp
Library/Source/NativeEngine.h

Call bgfx::shutdown() when destroying the NativeEngine

---

Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp
Apps/Playground/UWP/App.cpp
Apps/Playground/Win32/App.cpp
Apps/Playground/iOS/LibNativeBridge.mm
Apps/Playground/macOS/ViewController.mm
Apps/ValidationTests/Win32/App.cpp
Core/AppRuntime/Include/Babylon/AppRuntime.h
Core/AppRuntime/Source/AppRuntime.cpp
Core/JsRuntime/Include/Babylon/JsRuntime.h
Core/JsRuntime/Source/JsRuntime.cpp
Plugins/NativeEngine/Include/Babylon/NativeEngine.h
Plugins/NativeEngine/Source/InitializeNativeEngine.cpp
Plugins/ScriptLoader/CMakeLists.txt
Plugins/ScriptLoader/Include/Babylon/ScriptLoader.h
Plugins/ScriptLoader/Source/ScriptLoader.cpp
Plugins/XMLHttpRequest/Include/Babylon/XMLHttpRequest.h
Plugins/XMLHttpRequest/Include/Babylon/XMLHttpRequestApple.h
Plugins/XMLHttpRequest/Source/XMLHttpRequest.cpp
Plugins/XMLHttpRequest/Source/XMLHttpRequestApple.mm

Following up on initialization paradigm conversation, removed inheritance relationship from between AppRuntime and JsRuntime and adapted several plugins to (at least loosely) follow the new paradigm of requiring initialization on the correct thread.

Disassociate AppRuntime from JsRuntime

---

Dependencies/napi/source/js_native_api_JavaScriptCore.cc
Dependencies/napi/source/js_native_api_chakra.cc

A napi reference in the JSC implementation didn't actually stop the object from being garbage collected and was causing random crashes. This change fixes it.

Fix bugs in NAPI JSC implementation

---

.gitignore
Apps/Playground/Android/.gitignore
Apps/Playground/Android/app/CMakeLists.txt
Apps/Playground/Android/app/build.gradle
Apps/Playground/Android/package-lock.json
Apps/Playground/Android/package.json
Dependencies/napi/CMakeLists.txt
Plugins/XMLHttpRequest/Include/Babylon/XMLHttpRequest.h
azure-pipelines.yml

npm installation of JS engine
V8/JSC switch in Gradle
android pipelines for v8 and JSC
build instructions update in an upcoming PR

Android JS Engine selection

---

Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp
Apps/Playground/UWP/App.cpp
Apps/Playground/macOS/ViewController.mm
Apps/ValidationTests/Win32/App.cpp

I tried to add these calls in the right places, but it also seems like the existing deinitialization code was only partially done, so I tried to flesh it out where it seemed like it was missing as part of this change as well. I tested on Android, MacOS, Win32, and UWP. I haven't been able to get the iOS playground app to build or run yet.

Adding calls to DeinitializeGraphics to Playground apps

---

Apps/Playground/macOS/Base.lproj/Main.storyboard
Apps/Playground/macOS/ViewController.h
Apps/Playground/macOS/ViewController.mm
README.md

- CMD + R to refresh view (or via the File->refresh menu)
- command line arguments support (Product->scheme->edit scheme to edit command line arguments in Xcode)
- min requirements for ios/macos/android in readme
NB: .js files passed as command line arguments must point to files in content/resources of the application.
Tested with marbletower and default experience.js

Refresh and commandline support macos

---

Dependencies/AndroidExtensions/Include/AndroidExtensions/JavaWrappers.h
Dependencies/AndroidExtensions/Source/JavaWrappers.cpp
Dependencies/xr/Source/ARCore/XR.cpp
Plugins/NativeEngine/Source/NativeXr.cpp

This change is to handle display orientation changes for the ARCore-based XR support (as noted in #230). The primary changes are:
1. Creation of the textures moved from the constructor to GetNextFrame (it is done whenever the surface dimensions have changed (querying the surface dimensions is a ~12 microsecond operation, so I think it's ok to just check it every frame)).
1. Adding cleanup code to free the various resources (textures, shaders, etc.) that are allocated especially since some of these are now allocated every time the display orientation changes.
1. Exposing Android APIs to get the current display rotation through the JavaWrappers interfaces.
1. Moving around some more code to consolidate much of it to Session::Impl::GetNextFrame, and also moving the drawing code out of …

Handle display orientation changes in XR (ARCore specifically)

---

Apps/Playground/Android/app/CMakeLists.txt
Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp

When NativeXR got factored out to its own plugin, it didn't get added to the Android Playground app. With this change I'm adding it back.

Add back NativeXR to Android Playground

---

Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp
Apps/Playground/Android/app/src/main/java/BabylonNative/BabylonView.java
Apps/Playground/Android/app/src/main/java/BabylonNative/Wrapper.java
Apps/Playground/Android/app/src/main/java/com/android/babylonnative/playground/PlaygroundActivity.java
Dependencies/AndroidExtensions/CMakeLists.txt
Dependencies/AndroidExtensions/Include/AndroidExtensions/Globals.h
Dependencies/AndroidExtensions/Source/Globals.cpp
Dependencies/xr/Include/XR.h
Dependencies/xr/Source/ARCore/XR.cpp

This change adds three "events" to the Android `globals`: Pause, Resume, and RequestPermissionsResult. The first two are currently being used to pause/resume the ARCore session, and address one of the items in #230. I added the third because it was very similar to code I was already writing and @Alex-MSFT will need it for the permissions request stuff he is working on. I added a helper `Event` class, which could be moved to arcana, but I'm not sure if it will be used in the long term or not based on the AppLifecycle Core component we've discussed potentially adding, so I could go either way (leave it or move it to arcana).

Add Activity related events and support pause/resume in ARCore XR

---

Apps/ValidationTests/Scripts/validation_native.js
Apps/ValidationTests/Shared/TestUtils.h
Apps/ValidationTests/Win32/App.cpp
Apps/ValidationTests/X11/App.cpp
Polyfills/Window/Source/Window.cpp
azure-pipelines.yml

Run the tests provided in config.json and fails the build when image difference threshold is reached.
I successfully failed it by setting threshold to 0.

Enable validation tests on CI for Win32

---

Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp
Apps/Playground/Android/app/src/main/java/BabylonNative/Wrapper.java
Dependencies/AndroidExtensions/Include/AndroidExtensions/JavaWrappers.h
Dependencies/AndroidExtensions/Source/Globals.cpp
Dependencies/AndroidExtensions/Source/JavaWrappers.cpp

This change makes it the responsibility of `Globals` to manage the lifetime of the `jobject` referring to the app context. With the current implementation, it does this by first getting the application context from an arbitrary context, and creating a global ref from this jobject. The application context itself has the lifetime of the application, so in this case Globals just never cleans up this jobject (it will always exist, and reference an always existing application context).

Move app context jobject lifetime management to Globals

---

Plugins/NativeInput/Source/DeviceInputSystem.cpp
Plugins/NativeInput/Source/DeviceInputSystem.h
Plugins/NativeInput/Source/NativeInput.cpp
Plugins/NativeInput/Source/NativeInput.h

With this change the native contract for `DeviceInputSystem` matches the latest JS contract for `DeviceInputSystem`. The notable changes are:
- Devices are now identified by the DeviceType/DeviceSlot pair (rather than a string, e.g. "Pointer-0").
- There is now an event that fires whenever any input state changes.
Note that this still doesn't work in the sense of "overriding" the JS class. It seems it is not enough to just define a class with the same name and try to put it in the global scope. So as is, this class can be used/tested in the React Native repo by just not importing the JS `DeviceInputSystem` (in which case the native provides the implementation), but as soon as you import the JS version, then the native one does not replace the JS one. I need to think more about how to …

Update device input system to match the latest contract on the Babylon.js side

---

Dependencies/xr/Source/ARCore/XR.cpp

While adding XR support into the React Native integration layer, I found that the ARCore XR implementation did not work in this context. After some debugging, I found a couple issues:
1. Babylon intentionally does not clear the color texture each frame because whether or not it should be cleared is a detail of a specific XR implementation. For example, OpenXR provides a color texture that already contains the current camera frame, so you just draw your scene on top of it without clearing. In the case of ARCore, we use two separate textures - one for the camera frame, and one for the Babylon scene. So in this case, the ARCore XR implementation should clear the color texture each frame before Babylon draws the scene onto it.
1. When Babylon is rendering to an offscreen frame buffer (the …

[ARCore] Clear color/depth texture each frame, and explicitly present to the display

---

Dependencies/napi/source/js_native_api_chakra.cc

Added missing headers to js_native_api_chakra.cc to build properly in VS 16.6.0.

Added missing headers to js_native_api_chakra.cc

---

Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h

Prerequisite to move any GL shader work out of C++ and into Typescript as discussed with @CedricGuillemet for issue #211. Returns the bgfx RenderType enum as an int: returning a string would also be possible if that's more idiomatic!

Add a NativeEngine function to get current API (#211 groundwork)

---

Plugins/NativeInput/Source/DeviceInputSystem.cpp
Plugins/NativeInput/Source/DeviceInputSystem.h

We can't override classes with ES6+modules, so moving this into the `_native` object, and adding explicit code to the JS `DeviceInputSystem` to check for this (see https://github.com/BabylonJS/Babylon.js/pull/8225).

Move DeviceInputSystem from global scope to _native

---

Plugins/NativeXr/Source/NativeXr.cpp

Apparently it wants to be a world-space matrix instead of a view-space one.

Set matrix for view to not be view matrix

---

Dependencies/xr/Source/ARCore/XR.cpp

samplers were still the bgfx ones with mipmap enabled. but as we don't have MM for camera and Babylon texture, we ended up with a black rendering.
fixes #279

fix bound samplers arcore

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/ARCore/XR.cpp
Dependencies/xr/Source/OpenXR/XR.cpp
Plugins/NativeXr/Source/NativeXr.cpp

- bgfx keeps a list of framebuffers and update them when a resize happens
- in xr, when a resize happens, we delete the color/depth textures and create new ones : https://github.com/BabylonJS/BabylonNative/blob/a6384a810919697dd1f5186ef1d51cdd76e89266/Dependencies/xr/Source/ARCore/XR.cpp#L736
- bgfx frame buffer list contains an entry with a deleted texture. when trying to associate the deleted texture and the framebuffer object, there is an GL_INVALID_OPERATION error, trapped by bgfx as a fatal error
- the framebuffer with invalid texture exists because we never delete any framebuffer. we create a new one.
- the FB is added to a std::map here : https://github.com/BabylonJS/BabylonNative/blob/a6384a810919697dd1f5186ef1d51cdd76e89266/Plugins/NativeXr/Source/NativeXr.cpp#L325 but it's never …

fix rotation crash with XR and 0 sized texture (when locking the phone)

---

Plugins/NativeXr/Source/NativeXr.cpp

Updating to the latest release (4.2.0-alpha.21) of `babylon.max.js` (pulled from https://github.com/BabylonJS/Babylon.js/blob/9ddcddf942189345dc47190fe8a22fc7451b654f/dist/preview%20release/babylon.max.js). With this change, we can roll back the XR workaround for vector related changes.

Update Babylon.js, roll back XR workaround

---

Dependencies/xr/Source/ARKit/XR.mm

I'm not sure why, but `MainView.safeAreaLayoutGuide.layoutFrame` is zero in the context of React Native. However, we shouldn't try to accommodate the notch at this layer anyway. The owning view should do that, and we should make the subview match so that it just looks like we are drawing to the same view. For this, we can just use the `bounds`.
This change is related to #278

Use bounds instead of safe area

---

Dependencies/xr/Source/ARKit/XR.mm

This warning (treated as an error) only happens when compiling for the simulator, and is wrong, so we need to ignore it (since we treat warnings as errors). See https://stackoverflow.com/questions/59068464/cametallayer-is-only-available-on-ios-13-0.

Ignore incorrect warning

---

Dependencies/xr/Source/ARKit/XR.mm
Plugins/NativeXr/Source/NativeXr.cpp

Long story short, the aspect ratio is not good when creating the projectionMatrix because tan function is not linear.
So, I've added code to compensate the ratio deviation. I didn't want to do the change in NativeXR to not break the existing.

Compensate aspect ratio AR

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/ARKit/XR.mm

Implementing Create/Update/Delete support for anchors on ARKit.  This is the iOS equivalent of #289, and is part of the ARKit support described in #278.
This essentially works the same way as on Android.  We create a new ARKit anchor at the given pose, and update it once per frame as part of the WebXR update loop.  The main difference here is you cannot tie an ARKit anchor to a given plane, so we instead always create an independently tracked anchor whether we're given a hit result or not.

Anchors for ARKit

---

Dependencies/napi/napi-direct/source/js_native_api_JavaScriptCore.cc
Dependencies/napi/napi-jsi/include/napi/napi-inl.h
Polyfills/Window/Source/Window.cpp

Unicode conversion is a mess in C++. Using codecvt directly results in crashes on certain platforms. But using deprecated codecvt facets API works just fine.

Unicode fixes for NAPI/JSI

---

Core/AppRuntime/Source/AppRuntimeV8.cpp
Dependencies/napi/napi-direct/source/js_native_api_v8.cc

Disabled certain V8 warnings that were causing problems due to warnings being treated as errors. These errors were preventing usage of V8 by a partner team. Will open an issue to track this to determine whether we want to fix these warnings in our V8 implementation (which might introduce deviation from versions in other N-API repos), though even that wouldn't fix the warnings coming from the V8 files from the NuGet.

Disabled certain V8 warnings

---

Dependencies/xr/Source/OpenXR/XR.cpp

Incorrectly trying to turn on disabled features will crash the app either way if someone tries to enable plane detection so I think the right thing to do is just throw like all the other unsupported features.

Fix OpenXR debug build break in Plane Detection

---

Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h

fixes #358 
babylon.max.js version with commit https://github.com/BabylonJS/Babylon.js/pull/8697/commits/7dd3d8607015a4b95aec52039ee558092e981b54
PR on babylonjs : https://github.com/BabylonJS/Babylon.js/pull/8697
Use a vertex array object instead of binding individual streams
tested ok win32, Android and iOS

replaced bindbuffer function with bindvertexarray calls

---

Plugins/NativeXr/Source/NativeXr.cpp

This change changes the logic of XRViewerPose.Update to populate its transform with the pose of the first active view.
The XRViewerPose's transform is supposed to represent the position of the "Viewer" (i.e. phone, headset, or other tracked device) relative to a given reference space.  
This change assuming this pose is equal to that of the first active view.  This works for screen based viewers such as a phone or tablet, but is likely incorrect for devices with multiple views.  We will need to come up with a proper way to represent the viewer for these cases.

Change XRViewerPose.Update to set the transform of the ViewerPose

---

Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp
Polyfills/Window/Source/Window.cpp

Added handling in shader traverser for reshaping a level up when indexing into a type-adjusted uniform array. This allows Android to successfully render a single frame of alien head -- specifically the frame with the minimum number of morph target influences. There are other problems, including the placement of attributes at unallowably-high locations, which prevent the alien head from rendering more than a single frame on Android; those, however, are separate in origin and should probably be fixed in separate PRs.

Fix for one of the alien head problems on Android

---

Apps/Playground/Scripts/experience.js
Dependencies/xr/Include/XR.h
Dependencies/xr/Source/ARCore/XR.cpp
Dependencies/xr/Source/ARKit/XR.mm
Dependencies/xr/Source/OpenXR/XR.cpp
Plugins/NativeXr/Source/NativeXr.cpp

This is the BabylonNative half of Babylon.js change [#8724](https://github.com/BabylonJS/Babylon.js/pull/8724), which resolves #356.  This change enables hit testing against the three different supported entity types for WebXR: "plane", "mesh", and "point".
This just hooks up the API to the native hit test code for filtering our hit test queries.  The way I have represented the enum internally is as a bitfield enum to allow specifying multiple hit test target types.

Enable hit testing against different entityTypes in BabylonNative

---

Plugins/NativeInput/Source/NativeInput.cpp
Plugins/NativeInput/Source/NativeInput.h

It doesn't make sense to receive touch move events before touch down, but the touch position does need to be recorded before the touch start (logical) event is raised, so that an event handler can query the touch position. This change fixes this behavior.

Suppress x/y position events until after pointer down event

---

Plugins/NativeEngine/Source/NativeEngine.h

A preliminary fix to address (#362), we are removing the call to `bgfx::touch` which forces a clear even when no draw calls have been committed (clearing doesn't count for bgfx like it does in OpenGL, for example). This extra clear was clearing content drawn to the left eye texture for some VR HMD's (such as HP Reverb) and on HoloLens 2.

Remove bgfx::touch so that view clear doesn't clip stereo rendering

---

Dependencies/xr/CMakeLists.txt
Dependencies/xr/Source/OpenXR/XR.cpp
Dependencies/xr/Source/OpenXR/XrPlatformCommon.h

This change provides OpenXR implementations for the functions required for creating, updating, and deleting anchors through an XRFrame. Essentially an OpenXR analog to (#289).

Implement OpenXR anchoring polyfill

---

Dependencies/xr/Source/ARKit/XR.mm

XR was quite swimmy on iOS (as described in issue #74). With this change I am *attempting* to fix this. Unfortunately while it reduces the swimmyness, it still does not eliminate it, but I'm out of time for now to investigate this, so I want to check in this change since it is still an improvement.
The main change here is to try to switch from a "push" model for ARKit consumption to a "pull/poll" model. Practically what this means is to not implement the `didUpdateFrame` protocol in the `ARSessionDelegate`, and instead evaluate the `currentFrame` property of the `ARSession`. This basically makes it so ARKit only updates things when `currentFrame` is evaluated *and* a new camera frame has become available.
I can only get `currentFrame` to work correctly if called from the main thread, and …

Reduce XR swimmyness on iOS

---

Dependencies/xr/Source/OpenXR/XR.cpp
Dependencies/xr/Source/OpenXR/XrRegistry.h

A recent change to XR introduced the XrRegistry, which included a static member whose constructor depended upon the existence of an OpenXR runtime. This was causing the app to crash on initialization when running on a device without an OpenXR runtime because the constructor of the XrSessionContext would fail.
To avoid this, this PR switches from a static member to a global singleton, thereby avoiding static-ness as well. This isn't my favorite pattern, but it's the simplest adaptation I've thought of so far that behaves similarly to the original intent while not crashing if OpenXR isn't available. Definitely open to other designs, though, if a better one comes to mind.

Workaround for crash on startup on devices without XR runtimes.

---

.github/workflows/nightly.yml

Runs working days at 11pm
Checkout repo, download distpreview for babylonjs, build ValidationTests and runs it.
No configuration to do on the CI.

Github action for night build

---

Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp

Fixes #371, #372, #385.
Also fixes BabylonJS/BabylonReactNative#61 once BabylonReactNative picks up this change.
The main issue with the Android shader code path is that the sampler locations for textures are wrong. This change include a couple of fixes to address this:
1. The conversion to SPIRV is now as minimal as possible. The splitting of samplers into texture/sampler and then recombining them is now gone. [Removing SPIRV for OpenGL situations](https://github.com/BabylonJS/BabylonNative/issues/300) should be easier after this change. This is a problem because when SPIRV recombines the texture/sampler pair, it mangles the name and thus bgfx can't bind the locations properly. I couldn't find a way for SPIRV not to do this, but removing this splitting/recombining fixes this issue. …

 Fixes for Android shader compile

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/OpenXR/XR.cpp
Dependencies/xr/Source/OpenXR/XrSupportedExtensions.h
Plugins/NativeXr/Source/NativeXr.cpp

This change introduces the hand tracking backbone in XR.cpp and NativeXR.cpp to implement hand tracking when using openXR in BabylonNative. It works with the existing hand tracking code for BabylonJS, found [here](https://github.com/BabylonJS/Babylon.js/pull/8753).
This resolves #394

Implementing hand tracking via OpenXR for BabylonNative

---

Plugins/NativeEngine/Source/NativeEngine.cpp

Reworked the texture sampling variables in NativeEngine to try to more directly match the JavaScript and to be more easily parsed. I also ran an auto-format on NativeEngine.cpp while working on this (checking that my clang-format disable had worked as intended), and the format found a few other things it wanted to change, so I brought those along.
This PR depends upon https://github.com/BabylonJS/Babylon.js/pull/9033 and will be updated with a formal Babylon.js build and commit ID once that PR goes in.

Rework texture sampling variables in NativeEngine

---

azure-pipelines.yml

For an unkown reason, tests on Linux with Clang are timing out. When it happens in a PR, re-running the task works just fine.
I tried to change display export, update clang to v9,... without success.
No other choice than removing the CI tests for now.
Related issue : https://github.com/BabylonJS/BabylonNative/issues/426

Removed CI Validation Tests for Linux/Clang

---

Plugins/NativeEngine/Source/NativeEngine.h
Plugins/NativeXr/Source/NativeXr.cpp

Because of a vertical flip needed for render targets on Direct3D and Metal, XR rendertarget was also flipped.
But as it is used for direct use with particular UV on Metal and as back buffer on Windows, the 3D displayed was flipped.
For XR, the render target must behave like a back buffer and not like a render target that would be reused by a pixel shader.

fix XR renderTarget regression

---

Dependencies/napi/napi-jsi/include/napi/napi-inl.h
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h
Plugins/NativeInput/Source/DeviceInputSystem.cpp
Plugins/NativeXr/Source/NativeXr.cpp
README.md

Several changes were recently made that broke XR on Android and iOS, and this PR fixes them.
- NAPI JSI needs a `StaticAccessor` implementation that doesn't throw and a `Reference::Reset` that is functional. I think there is more we need to do to actually make `StaticAccessor` work rather than just not crash. If that's the case, I can add a comment or something.
- NativeEngine needs to clear out the `RequestAnimationFrame` callback after calling it so that when we transition to XR mode we don't end up rendering twice (e.g. calling the stale callback for the regular `RequestAnimationFrame` in addition to the current callback for the XR `RequestAnimationFrame`).
- `DeviceInputSystem` needs to access the JS native object via the new `NativeObject` class.
- NativeXR should use the `Set` …

Fix some regressions in XR mode on Android and iOS

---

Core/Graphics/Source/Graphics.cpp

fixes #390 
bgfx reset flags was not sent to bgfx::reset

vsync Android

---

Plugins/NativeWindow/Include/Babylon/Plugins/NativeWindow.h
Plugins/NativeWindow/Source/NativeWindow.cpp

We currently have no way to update the `windowPtr` held by `NativeWindow`, even though the window can in fact change through the lifetime of Babylon Native. `NativeXR.cpp` relies on `NativeWindow` to pass down the `windowPtr`. The iOS XR implementation (`XR.mm`) uses this to get the size, and also to create a sub view for the XR rendering. This means that if the `windowPtr` changes (e.g. disable and reenable the view in Babylon React Native), it operates against the original `windowPtr`, and things blow up. So this change just adds a `Reinitialize` function to `NativeWindow`, which I will call in the React Native integration layer.
This caused https://github.com/BabylonJS/BabylonReactNative/issues/57 to still repro (from a different root cause) on iOS.

Add Reinitialize function to NativeWindow

---

Plugins/NativeXr/Source/NativeXr.cpp

Attempt to fix scheduling problems with animation frame requesting for scenarios where the creation of XR predates the creation of the render loop. Without this change, if there was no pre-existing render-loop, there was a one-frame gap before XR's render loop would become self-sustaining, and consequently it would never get started in earnest. I believe this may be the fix, or a meaningful part of it, for the recent soft-lock issues encountered by several teams consuming Babylon Native for XR on multiple platforms. I don't have access to all the required platforms, though, so further testing is needed to ensure this actually fixes the problem.

XR animation frame request scheduling bug fix

---

Plugins/NativeXr/Source/NativeXr.cpp

Also replacing the push_back call with an emplace_back call, for a slight efficiency bonus.
Fixes #435

Checking the added anchor at its new location

---

Core/AppRuntime/Source/AppRuntimeChakra.cpp

Visual Studio currently doesn't deploy the required binaries needed for JS debugging on ARM-based platforms such as HoloLens 2. While we wait for the required VS fixes, this change disables the `JsStartDebugging` call on those architectures.
Related to #409

Disable Chakra debugging on ARM platforms

---

Dependencies/UrlLib/Source/Apple/UrlRequest.mm
Plugins/NativeEngine/Source/NativeEngine.cpp
README.md

fixes #292 
- Added a comment for building MacOS with Xcode 12
- Correctly thow an exception that is catched by JS when unable to decode image
- throw when a missing resource in app bundle 
engine.createTexture("https://url_to_an_invalid_image"); is correctly trapped with an error in the JS console (by the thow line 1087 n NativeEngine.cpp)
but
engine.createTexture("app:///invalidResource.png"); is not trapped and the program stops despite the throw line 49 in UrlRequest.mm
I tried to see what's the difference but I was not able to put a finger on it. Any clue @bghgary ?

throw runtime_error on bad image data or missing app bundle resource

---

Dependencies/AndroidExtensions/Include/AndroidExtensions/JavaWrappers.h
Dependencies/AndroidExtensions/Source/JavaWrappers.cpp
Dependencies/UrlLib/Source/Android/UrlRequest.cpp
Polyfills/XMLHttpRequest/Source/XMLHttpRequest.cpp
Polyfills/XMLHttpRequest/Source/XMLHttpRequest.h

This change both (slightly) improves implementation details of `XMLHttpRequest` on Android, and also makes it possible for Babylon.js to use Babylon Native's `XMLHttpRequest` even in the context of React Native (which provides it's own problematic `XMLHttpRequest`).
- In `JavaWrappers` expose the `ByteArrayOutputStream` constructor that takes an initial size. Otherwise if we start at zero, the heuristic for growing the underlying buffer is very aggressive and ends up way over allocating and causing too much memory pressure.
- In `JavaWrappers` expose the `URLConnection.GetContentLength()` function. Sometimes this will provide too small a value (e.g. compressed streams) or no value (when its not known), but it gives us a good chance of getting the actual size so we can pass it to …

XMLHttpRequest related improvements

---

Dependencies/xr/Source/ARKit/XR.mm

The main issue being fixed here is that after
`id<MTLTexture> texture = [metalDevice newTextureWithDescriptor:textureDescriptor];`
We need an explicit call to `retain`. In Cocoa, these static factory functions always call `autorelease` for the object being constructed, which means `release` will automatically be called when the containing `@autoreleasepool` scope exits. However, we previously didn't have an `@autoreleasepool` scope because we were managing the JS thread scheduling ourselves (and I didn't understand memory management patterns with Objective C and Cocoa). React Native's `CallInvoker::invokeAsync` does this correctly by wrapping the call to the function passed to it in an `@autoreleasepool`. What this means is that the `@autoreleasepool` is actually auto releasing the …

Fix a few memory management issues in xr.mm

---

Dependencies/xr/Source/ARKit/XR.mm
Polyfills/XMLHttpRequest/Source/XMLHttpRequest.cpp
Polyfills/XMLHttpRequest/Source/XMLHttpRequest.h

This change addresses leaking the platform agnostic byte buffer as well as the platform specific byte buffer of the downloaded file. So for example, when loading the 5.5mb Surface Pro model, we were leaking about 11mb for each load. There were a couple issues:
1. We didn't have the `loadend` event, which the Babylon.js side uses to complete certain operations and let go of the `WebRequest` that wraps the `XMLHttpRequest`. I added this event.
1. We hold `FunctionReference`s to the event handler callbacks, which are strong references that prevent the JavaScript garbage collector from collecting an otherwise unrooted object graph. I'm now clearing out the event handlers after the request completes.
This partially addresses https://github.com/BabylonJS/BabylonReactNative/issues/102. The other …

Fix XMLHttpRequest memory leak

---

Polyfills/XMLHttpRequest/Source/XMLHttpRequest.cpp
Polyfills/XMLHttpRequest/Source/XMLHttpRequest.h

Empirical evidence suggests this change caused the CI validation tests to become flakey. Rolling it back for now while we investigate.

Roll back XHR fix to see if it fixes CI flakeyness

---

Plugins/NativeEngine/Source/NativeEngine.cpp
Polyfills/XMLHttpRequest/Source/XMLHttpRequest.cpp
azure-pipelines.yml

There were a couple of problems with our lifetime management of buffers obtained through `XMLHttpRequest` that contain texture data loaded asynchronously:
1. The native memory was managed by the lifetime of the underlying `UrlRequest`, owned by the native `XMLHttpRequest`. If the JavaScript side asks for the `ArrayBuffer` of the downloaded data and holds onto it but doesn't hold onto the `XMLHttpRequest`, then that native memory is deleted from under us and we end up accessing deleted memory while asynchronously loading a texture (or possibly other data). The fix for this for now is to make a copy of the data into the `ArrayBuffer` so the JS side can own it. We could improve on this by ref counting the native memory, but we should address that with #445.
1. The native code that does the …

Fix texture data lifetime management issues

---

Dependencies/xr/CMakeLists.txt

CI machines now resolve jsoncpp based on C:/msys64/mingw64/lib/cmake/jsoncpp, which did not exist before. This change updates our cmake to never use system resolve jsoncpp

Set cmake overrides for OpenXR-SDK's jsoncpp dependency to unblock ci build

---

Apps/Playground/X11/App.cpp
Apps/ValidationTests/Win32/App.cpp
Apps/ValidationTests/X11/App.cpp

Ensure all validation tests are calling fflush after printf so that logs are accurate after a crash.

fflush after printf

---

Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h

ScheduleRender is not thread-safe. We can either make it thread-safe or only call it from one thread. I've chosen the latter for now. We can revisit if necessary.
This should fix the intermittent issues we are having in the CI.

Ensure NativeEngine::ScheduleRender is called from the JS thread

---

Dependencies/UrlLib/Source/Unix/UrlRequest.cpp
Plugins/NativeEngine/Source/NativeEngine.cpp
azure-pipelines.yml

Ubuntu fails a lot because of timeout. It looks like we are running with a debug build. This change makes it build the RelWithDbgInfo configuration.
Also fixes a couple of warnings as error for unused variables.

Build RelWithDebInfo in CI

---

Polyfills/Window/Source/Window.cpp

Right now setTimeout(0) executes synchronously. This breaks logic in Babylon.js. In this change we force all setTimeout callbacks to have to occur on the next frame.

small fix to setTimeout

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/ARCore/XR.cpp
Dependencies/xr/Source/ARKit/XR.mm
Dependencies/xr/Source/OpenXR/XR.cpp
Plugins/NativeXr/Source/NativeXr.cpp

We were previously just passing a `void* windowPtr` into the XR layer (specifically for iOS/ARKit right now), but this isn't good enough since the window can change during an XR session. The change here is to instead pass in a `std::function<void*()> windowProvider` so the XR layer can query the current window. This happens inside `GetNextFramed`, which is similar to what the ARCore XR layer does (it polls the current gl surface on each GetNextFrame). This addresses https://github.com/BabylonJS/BabylonReactNative/issues/106. Note the reason it was *crashing* before is because we immediately released the `xrView` and allowed the superview to manage its lifetime, but the superview (the window) can be replaced, in which case the `xrView` is released and we continue to try to use it. Now we …

Support updating window in ARKit XR

---

Dependencies/AndroidExtensions/Include/AndroidExtensions/JavaWrappers.h
Dependencies/AndroidExtensions/Source/JavaWrappers.cpp
Dependencies/UrlLib/Source/Android/UrlRequest.cpp

With the current implementation of UrlRequest for Android it does not support loading local files. When using a URL in the format of `file://<local_path>` Babylon-Native crashes on Android (but does work on iOS).
The root cause of the crash is because of an incorrect cast from UrlConnection to HttpUrlConnection where depending on the URL the underlying class may be a FileUrlConnection. This change matches the iOS implementation where it checks if the UrlConnection is of the type HttpUrlConnection and if so it checks the response code. If the UrlConnection is of any other type it returns HTTP 200. I verified that if you give it a local file url that is invalid it gracefully handles the error and properly returns a status code of 0.
In order to accomadate the ability to check the java class …

Fixing the UrlRequest on Android for local files

---

Apps/ValidationTests/Scripts/config.json
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h

This PR improves the logic around managing view id assignments for framebuffers: 
* Assign new view id's per-frame instead of per-bind, and notify framebuffers of dirty view id's by maintaining a table of self-destructible weak references.
* Set the view rect to the size of the framebuffer by default, and conditionally set the size to match the window, instead of always just sizing to the window, since in XR we aren't always rendering to a window-sized backbuffer.
* Keep the default backbuffer assigned to view id 0 in order to stay consistent with bgfx's convention. This is strictly better than what we were doing before (assigning `BGFX_INVALID_HANDLE` to view id 1) because we were effectively assigning two view id's to the default backbuffer, one through default bgfx behavior and one …

Improve framebuffer view logic

---

Dependencies/AndroidExtensions/Include/AndroidExtensions/JavaWrappers.h
Dependencies/AndroidExtensions/Source/JavaWrappers.cpp

- Release char buffers after we are done with them (e.g. copying them into an std::string).
- Don't return a pointer to a stack allocated char buffer from Throwable::what (instead store the message as an std::string in the Throwable).

Small fixes in JavaWrappers

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/ARCore/XR.cpp
Dependencies/xr/Source/ARKit/XR.mm
Dependencies/xr/Source/OpenXR/XR.cpp
Plugins/NativeXr/Source/NativeXr.cpp

This PR attempts to address #473, which effectively expanded the projection matrix to maintain the aspect ratio, but incorrectly calculated the real FOV.  I think this was occurring because we were applying both the angle FOV values with the aspect ratio from the color texture.
In this PR I'm pushing the generation of projection matrices down to the platform level implementations.  For ARCore and ARKit we are provided with valid projection matrices.  For OpenXR we need to generate them ourselves based off the FoV angles.
Here are some comparisons from my testing attempting to measure a 5' long measuring tape.  In both cases I measured by getting close to the tape and walking along its length then stepping back to a reasonable distance to take a picture.
old:
new:

Push XR projection matrix generation down to platform implementations

---

Core/AppRuntime/Source/AppRuntimeChakra.cpp
Core/AppRuntime/Source/AppRuntimeJavaScriptCore.cpp
Dependencies/napi/napi-direct/source/js_native_api_chakra.cc
Dependencies/napi/napi-direct/source/js_native_api_chakra.h
Dependencies/napi/napi-direct/source/js_native_api_javascriptcore.cc
Dependencies/napi/napi-direct/source/js_native_api_javascriptcore.h
Dependencies/napi/napi-direct/source/js_native_api_v8.h
Plugins/NativeEngine/Source/NativeEngine.cpp

As part of #480 we introduced a bug where the NAPI references are not being destructed on the JS thread. This change moves the capture of the NAPI references further down the task chain so that it ends up on a JS thread continuation. This is the result of investigating #510, but I have not confirmed if the issue is fixed yet.
To make sure this type of thing never happens again, this change also adds thread checking logic to each of the NAPI direct implementations (Chakra, V8, JSC). There is more work to do to implement this in NAPI/JSI, but since NAPI direct has the check, it will be much less likely to have a NAPI/JSI specific threading issue.

Threading fixes

---

Dependencies/xr/Source/OpenXR/XR.cpp

We were using the MS controller bindings and defaulting to default bindings when they weren't accessible, but this creates a problem. Aim/grip space is only populated when the input device is a MS controller, and other devices, such as hands, do not populate aim/grip space.
Also, if the default profile *was* used, xrSuggestInteractionProfileBindings would hit an error as the list of bindings included invalid bindings for the default profile.

Enabling default and microsoft controller bindings side-by-side

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/OpenXR/XR.cpp

Since the action profile's availability is separate from whether we use it, this change only creates a gamepad component on the input source if gamepad data is available.

Only creating gamepad data when gamepad information is available

---

Dependencies/xr/Source/ARCore/XR.cpp
Dependencies/xr/Source/ARKit/XR.mm

This change is the first part of the solution to #562.
Prior to this change, we would clear the render texture, have Babylon render to it, then in a custom shader compose the Babylon render texture on top of the camera texture. The problem with this is that BGFX never sees the camera texture, and so there is no way from the context of Babylon Native to get an rgba byte buffer of what is being displayed to the screen in XR mode.
With this change, for both ARCore and ARKit, we now draw the camera texture onto the render texture that Babylon draws to, and then we just present that final texture to the screen. This way the render texture that Babylon Native (and therefore BGFX) is dealing with has the camera texture.
I did a little bit of white space and uniform initialization cleanup as …

Draw AR camera to babylon render texture

---

Plugins/NativeInput/Source/NativeInput.cpp
Plugins/NativeInput/Source/NativeInput.h

Prior to this change, when an input state change happened, there would be a sequence of updating state and raising a state change event all interleaved. This causes problems when one of those event handlers tries to query state that isn't updated yet. With this change, group of state get updated, then a batch of state changes are fired together. This makes the API behave the same as in the browser, and fixes https://github.com/BabylonJS/BabylonReactNative/issues/124.

Raise input events after all input state is updated

---

Core/Graphics/Source/Graphics.cpp

Add an explicit bgfx::discard() call on resize to ensure that the internal state of bgfx has been reset.
fixes #581

Fix texture binding related exceptions caused by resize

---

Dependencies/xr/Source/ARKit/XR.mm

This PR contains logic that surfaces feature points from ARKit on iOS. This replicates the logic that @Alex-MSFT added for ARCore back in August: https://github.com/BabylonJS/BabylonNative/pull/353.
This'll allow the applications consuming this logic to get the same experience with feature points on iOS as they currently have on Android, and furthers the feature parity across platforms.

Expose AR Feature Points on iOS

---

Plugins/NativeInput/Source/Android/NativeInput.cpp
Plugins/NativeInput/Source/iOS/NativeInput.cpp

BabylonNative PR ci doesn't build NativeInput, but BabylonReactNative is seeing android and ios build failures due to slash direction

Fix slash direction

---

Dependencies/napi/napi-jsi/include/napi/napi-inl.h
Dependencies/napi/napi-jsi/include/napi/napi.h

This review makes some changes to implement static methods/accessors for DefineClass calls. It also ensures that property descriptors are populated correctly for some different instance methods.
This addresses some issues here: https://github.com/BabylonJS/BabylonNative/issues/329

Fill in some missing napi static definitions

---

Apps/Playground/CMakeLists.txt
Apps/ValidationTests/CMakeLists.txt
Plugins/NativeEngine/Source/NativeEngine.cpp

Some teams can use this flag for macos/ios build. Adding it to the CI will check that some symbols are defined mutiple times accross the libs.

add all_load flag for apple targets

---

Core/Graphics/Source/Android/GraphicsPlatform.h

As of recent changes, the actual render loop is managed by the consumer of the Babylon Native API. Currently consumers are *required* to run the render loop on the main thread. Pretty much any way you do that on Android, the main thread is already blocking on vsync, so having bgfx also block on vsync results in a double vsync block that impacts perf. For now, I'm just removing this flag. As soon as @Drigax's changes are in that make `CreateGraphics` take a configuration, we should add vsync to that, because we'll want to be able to choose to enable it when we have a dedicated render thread. But for now, this unblocks performance regressions on Android.

Disable vsync on Android

---

Dependencies/xr/Source/ARCore/XR.cpp

This change fixes #647. For some reason, creating a parent `EGLContext` (with the bgfx `EGLContext` as a child) doesn't work correctly on some devices (maybe a driver issue?). We don't really *need* this parent context though, it was just a defensive measure to try to ensure we don't pollute the `EGLContext` "owned" by bgfx. For now, I'm just removing this as it seems to fix the issue.

Fix ARCore rendering regression

---

Dependencies/xr/Source/OpenXR/XrSupportedExtensions.h

Right now an xrcheck throws crashing the app when openxr resources aren't installed. this change should fail silently.

Fix initialization when openxr resources aren't available

---

Apps/ValidationTests/iOS/LibNativeBridge.h
Apps/ValidationTests/iOS/LibNativeBridge.mm
Apps/ValidationTests/iOS/ViewController.swift
Plugins/NativeEngine/Source/ShaderCompilerCommon.cpp
Plugins/NativeEngine/Source/ShaderCompilerMetal.cpp
azure-pipelines.yml

- enable decoration bindings for Metal texture association
- update SPIRV
- update iOS validation tests
- enable GCC10 build on AzurePipelines fixes #679

GCC10 + Latest SPIRV-cross

---

Plugins/NativeEngine/Source/NativeEngine.h

Default webgl context has culling and depth test disabled. 
But ThinEngine enable them in the constructor. NativeEngine does not and assume those states to be on by default.
One of our partners, using a specific ThinEngine, doesn't do calls to enable and a different behavior arise with NativeEngine.
Until ThinEngine and NativeEngine are using same behavior (making PRs on .js and native will take some days), I prefer to revert this change as it may introduce regressions in some rendering for most of our other partners.

revert m_engineState

---

Dependencies/v8inspector/CMakeLists.txt

asio is a header-only library included as an INTERFACE target, and CMake doesn't allow the FOLDER property to get set on INTERFACE's, so we'll just remove the line.
fixes #747

Don't set folder property on asio library

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/OpenXR/Windows/XrPlatform.h
Plugins/NativeXr/Source/NativeXr.cpp

This is the first small change to improve XR rendering performance on Windows Mixed Reality devices.
We need to use the [recommended backbuffer formats](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-best-practices#select-a-swapchain-format) for rendering, which means a depth buffer format without any stencil bits. This will get us closer to using the "PassThru" OpenXR compositor mode (right now we're using "TexMapping"), which will basically evaporate the Post CPU/GPU portion of the frame times listed below.
An important callout here is that there currently isn't any way for a WebXR user to specify what format they want the runtime to use when creating its swapchains. We also currently have no way of specifying backbuffer formats for NativeEngine (including …

Prefer non-stencil depth for WMR

---

Apps/Playground/Scripts/experience.js

We were creating a Color4 from a Color3, and the Color4(Color3) constructor assigns alpha to 1.0, causing the background to be semi-opaque in mixed reality captures.
fixes #652

Use transparent clear color on HoloLens

---

Plugins/NativeXr/Source/NativeXr.cpp

This reverts commit e2e409d6038c3d5e9f3c286c88f1741432230f84.
Fixes regression #755

Revert "Don't try to create new XR textures if no window (#746)"

---

Plugins/NativeEngine/Source/ShaderCompilerD3D.cpp

In the case of illegal shader syntax, it looks like the compiler error message is retrieved by `getInfoLog()` while `getDebugInfoLog()` retrieves the empty string, so I swapped them out.

Changed the source of the shader compilation error message.

---

Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp

Fix for bug #734. Needs a [glslang update](https://github.com/KhronosGroup/glslang/pull/2653) before it can go in.

Fix for shader traverser crash

---

Dependencies/xr/Source/ARKit/XR.mm
Plugins/NativeXr/Source/NativeXr.cpp

This fixes #785. There are two small changes:
- In XR.mm use the `deletedTextureAsyncCallback` when cleaning up the depth texture (same as what we were doing for the color texture).
- In NativeXR.cpp switch back to the render thread before completing the `deletedTextureAsyncCallback` async operation so that code that does an inline continuation will execute on the render thread (e.g. where the texture is released).
I tested this in debug/release for both Android/iOS, but no coverage on Windows.

Fix iOS XR mode crash on device orientation change

---

Dependencies/xr/Source/OpenXR/SceneUnderstanding.cpp
Dependencies/xr/Source/OpenXR/XrSupportedExtensions.h

`XR_MSFT_SCENE_UNDERSTANDING_PREVIEW3` has moved to `XR_MSFT_SCENE_UNDERSTANDING`.
Updated our OpenXR submodules to pick up the new headers and helper code, and renamed a couple variables on our side.

Update OpenXR to support non-preview SU

---

Plugins/NativeEngine/Source/NativeEngine.cpp
Polyfills/Canvas/CMakeLists.txt
Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Canvas.h

Defining a second TextureData definition for the Canvas seemed to resolve correctly in BabylonNative. But in BabylonReactNative the jsi wrapper unwrapping the external type threw exceptions. This change updates the Canvas polyfill to consume the TextureData struct defined by NativeEngine. It seems like this is what we should be doing to avoid getting into scenarios where the struct definition changes and we need to update multiple locations.
We also update loadTTF to only load a font once. Once a font is getting used if its updated on the js thread it can cause crashes for the graphics thread.
Note: this change requires having the Canvas polyfill reference internal headers for NativeEngine. It seems like this is already an expected practice. I'm not sure if polyfills are supposed to …

Use the NativeEngine TextureData definition to avoid crashes unwrapping Napi::External<NativeEngine::TextureData> for jsi

---

Apps/ValidationTests/iOS/LibNativeBridge.mm

Missing Canvas init for iOS ValidationTests

Fix Missing Canvas Init VT iOS

---

Apps/Playground/Win32/App.cpp

Fixes #817 
SC_RESTORE event happens when un-maximizing. Previously this event assumed it was only called when app was minimized.
Checking it was minimized before otherwise does nothing.
WM_SIZE event occurs anyway.

Fix Win32 crash unmaximized

---

Core/Graphics/Source/FrameBuffer.cpp
Core/Graphics/Source/FrameBuffer.h
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeXr/Source/NativeXr.cpp
Polyfills/Canvas/Source/Canvas.cpp

With Metal, having a stencil operation or depth write on a RenderTarget that does not have a Depth/stencil buffer will pop up an error with Metal Validation Layer. (I guess it will be the same with Vulkan)
So, keeping track of depth/stencil capability for the frame buffer and enable/disable feature accordingly.

Check Stencil/Depth RT

---

Apps/Playground/Scripts/experience.js
Dependencies/xr/Source/ARKit/XR.mm

Functionality for producing ARKit LiDAR mesh geometry data was added. ARKit uses the LiDAR scanner to create a polygonal model of the physical environment. This data will allow the user to more accurately locate points on real-world surfaces. 
- Available on devices with a LiDAR scanner that support scene reconstruction, running iOS 13.4 or later.

Added functionality for producing ARKit LiDAR mesh geometry data

---

Plugins/NativeEngine/Source/NativeEngine.cpp

I made a silly mistake when creating a custom shader where my uniforms array looked like this:
```javascript
var uniforms = [
"world", "viewProjection", "cameraPosition",
, "_Radius_", "_Line_Width_", "_Absolute_Sizes_", "_Filter_Width_"
];
```
Causing the array to have a `,,` entry, and causing `NativeEngine::GetUniforms` to crash. This didn't cause an issue in Babylon.js, so I figured it would be good for us to handle the error case gracefully as well.
Alternatively, we could throw an error telling the user to check their uniforms array (since it's highly unlikely that they wanted to pass a non-string), but that would be different behavior from BJS.

Handle non-string uniforms

---

Dependencies/xr/Source/OpenXR/XR.cpp

fixes #830 and cleans up some of the logic around secondary view configurations.

Fix Mixed Reality Capture for HoloLens

---

Dependencies/UrlLib/Source/Windows/UrlRequest.cpp

On Windows, UrlRequest would generate a crash when calling ResponseBuffer() if the response buffer was undefined. This fixes that by returning an empty object instead.

Fix UrlRequest Response Buffer Crash

---

Apps/package-lock.json
Apps/package.json

The main purpose of this upgrade is to pull in the changes that take advantage of the new NativeOptimizations plugin.
I also downgraded the package lock to version 1 (by using npm 6 instead of 7) to be consistent with Babylon React Native.

Update to Babylon.js 5.0.0 alpha 34

---

Dependencies/xr/Source/ARKit/XR.mm

In https://github.com/BabylonJS/BabylonNative/pull/850, changes were made to clear the depth/stencil texture. However, the pipeline state did not match the render pass descriptor, which on my device causes metal API validation failures in debug and a crash in release. To fix this, the pipeline state needs the depth/stencil pixel format defined. However, we don't use depth/stencil when drawing the final texture to the screen, so we need two different pipeline states (one for drawing the camera color/depth/stencil texture, and one for drawing the final texture to the screen).

More fixes for iOS XR rendering

---

Dependencies/CMakeLists.txt
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h

Fix bug reported by @Alex-MSFT 
- Enable blit emulation for OpenGL (blit not natively supported on Android Emulator. Good catch Alex!)
- Fix BLIT flag for textures. Texture was recreated each frame and made the blit to fail when updating the canvas each frame.

Fix Dynamic texture flag for Canvas

---

Apps/UnitTests/CMakeLists.txt
Apps/UnitTests/Scripts/tests.js
Apps/UnitTests/UnitTests.cpp

Removes GoogleTest dependency and C++ tests for UrlLib. In their place, adds basic Javascript tests for XMLHTTPRequest using Mocha.js and Chai.js.
Includes several hacks that should be cleaned up, marked with TODOs.
Creates base framework for #802.

Replace C++ GoogleTest tests with JS tests using Mocha and Chai

---

Apps/Playground/UWP/App.cpp
Apps/Playground/Win32/App.cpp

We need to comment out the lines loading recast.js on Win32 and UWP because v8jsi is currently incompatible with asm.js scripts.
I also forgot to add a comment explaining why we were commenting out the file.

Comment out recast.js on windows

---

Dependencies/AndroidExtensions/Include/AndroidExtensions/OpenGLHelpers.h
Dependencies/xr/Source/ARCore/XR.cpp
Plugins/NativeCamera/Source/Android/NativeCameraImpl.cpp

Also
- Removed all the transactions except for eglMakeCurrent
- Set all states before blitting textures
Addresses partially #871. We still need the Babylon.js side to not do the clear when in XR.

Clear depth and stencil on the camera frame buffer

---

Apps/package-lock.json
Apps/package.json

Fixes #871
This is the last step to fixing the problem. It brings in a change that will not call clear for `immersive-ar` scenarios.
Testing:

 Update to babylonjs 5.0.0-alpha.44

---

.github/workflows/nightly.yml

Adds steps to download Mocha.js and Chai.js as part of the nightly build. This fixes the error that is currently being thrown when trying to build UnitTests, which depends on these files.

Add mocha.js and chai.js to nightly

---

Apps/Playground/iOS/LibNativeBridge.mm
Apps/Playground/macOS/ViewController.mm

Initializes the Console polyfill on MacOS+iOS and uses NSLog to print the messages.

Add console logging to the Playground App on Apple Devices

---

Dependencies/UrlLib/CMakeLists.txt
Dependencies/UrlLib/Source/Apple/UrlRequest.mm

~~Currently, we are storing a pointer to an NSURL object when we call Open(), and then creating the URLRequest in SendAsync(). The problem is that it's possible for the underlying object to be released in between these calls. This fix simply increments the refCount on Open() and then decrements it when the object is destroyed or when Open() is called again.~~
Makes UrlLib use Automated Reference Counting: https://en.wikipedia.org/wiki/Automatic_Reference_Counting
This way, we no longer have to manually retain/release objects.
Also, stops storing the URL from Open() as a member variable unless it's a valid URL. If it's a bad URL, we should not be retaining it.

Fix Apple Memory Management Bug in UrlLib

---

Dependencies/CMakeLists.txt
Dependencies/xr/Include/XR.h
Dependencies/xr/Source/ARCore/XR.cpp
Dependencies/xr/Source/ARKit/XR.mm
Dependencies/xr/Source/OpenXR/XR.cpp
Plugins/NativeXr/Source/NativeXr.cpp

Previously, xr.mm used a different `MtlCommandQueue` from bgfx, which basically means the xr.mm command queue needed to be fully drained before the bgfx command queue started processing, and then the bgfx command queue needed to be fully drained before the xr.mm presented the final render texture to the display, and both of these were done by blocking the main thread while waiting for queues to drain. This resulted in a lot of blocked time that increased frame time unnecessarily. The fix is to use the same command queue as bgfx and remove the blocking operations, which ensures things happen in the right order and happen as efficiently as possible.

Remove thread blocking operations in XR mode on iOS by sharing a command queue with bgfx

---

Polyfills/Canvas/Source/Colors.h
Polyfills/Canvas/Source/Context.cpp

Parses strings of the form "rgb(#,#,#)". Does not currently support rgba() strings; I'm happy to add support for those later if we need them. Needed for LensRenderingPipeline.

Parse rgb() color strings in Canvas polyfill

---

Plugins/NativeEngine/Source/ShaderCompilerD3D.cpp
Plugins/NativeEngine/Source/ShaderCompilerMetal.cpp
Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp
Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp
Plugins/NativeEngine/Source/ShaderCompilerTraversers.h

This PR is a first pass at cleaning up the shader compiler code. The main change is to remove the preprocessor directives for VertexVaryingInTraverser, and replace them with separate subclasses classes. Since OpenGL and Metal use the same logic, they both share a subclass, while DirectX has it's own.
This approach seemed like the best way to get rid of preprocessors while still minimizing code duplication.
I left the IF_NAME_RETURN_ATTRIB macro in because there didn't seem to be much benefit to factoring it out; I could have rewritten it with a list and iterated over that, but I think the current solution is pretty readable as is.
(Also, sorry about the messy commit history; this branch diverged a bit from master and rebasing seems to have left a bunch of extraneous commits)
Resolves #914

Refactor Shader Traversers

---

Apps/Playground/iOS/LibNativeBridge.mm

Fix my goofy order-of-operations gaffe in iOS Playground

---

Dependencies/UrlLib/Source/Android/UrlRequest.cpp

In response to this thread: https://forum.babylonjs.com/t/error-cannot-load-cubemap-because-6-files-were-not-defined/24852/50
Throws a clearer error message if you try to open a URL without a scheme

Android UrlLib: throw if scheme is null

---

Dependencies/xr/Source/ARCore/XR.cpp

By default, ARCore camera mode is set to fixed. To enable auto focus, configure the ARSession with auto focus mode
Addresses: https://github.com/BabylonJS/BabylonNative/issues/731

Configure ARCore auto focus mode

---

Dependencies/napi/napi-jsi/include/napi/napi-inl.h
Dependencies/napi/napi-jsi/include/napi/napi.h

There is an issue with using jsi host objects as prototypes on react native windows. This change works around the problem by using a side property instead of chaining the prototype. Using prototype chaining is perhaps not a good idea anyways since it introduces another layer when accessing arraybuffer members.

Fix an issue with array buffer finalizers for napi/jsi implementation

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/ARCore/XR.cpp
Dependencies/xr/Source/ARKit/XR.mm
Dependencies/xr/Source/OpenXR/XR.cpp
Dependencies/xr/Source/OpenXR/XrInput.h
Plugins/NativeXr/Source/NativeXr.cpp

Use spaces instead of plain poses on anchors to more closely match the XR API's we work with, remove the implication that a space is a frame-bound construct (the pose attached to the space is frame-bound), and allow us to store `anchorSpace` as a property on the anchor object rather than exposing it through an accessor function to improve performance.

Switch anchor pose for space

---

Plugins/NativeXr/Source/NativeXr.cpp

This is the first step towards native support of the [WebXRLayers feature](https://github.com/BabylonJS/Babylon.js/blob/06257deb5a3481652582ea6d6e4ee7638b02d60d/src/XR/features/WebXRLayers.ts) and fixes a rendering bug on mobile caused by [this change](https://github.com/BabylonJS/Babylon.js/pull/11631).

Define XRWebGLBinding

---

Dependencies/xr/Source/ARKit/XR.mm

We used to block the command buffer until it completed, and then set texture resources to purgeable. To improve performance, we removed the blocking, but that left the code in a state where we end up making texture resources purgeable before the command buffer completes. I guess we got lucky that this didn't seem to cause a problem in release builds, but in debug builds with Metal API validation enabled these issues are flagged and the debugger stops app execution.
The change here is to ensure that texture resources are made purgeable only after the command buffer completes.
Fixes #932

Fix xr.mm texture cleanup timing issues

---

Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp

Fixes #959. Tested on Windows D3D11 using the repro described in the bug.

Handle selection node fixing repro for shader compilation bug.

---

Core/Graphics/Source/GraphicsImpl.cpp

Supercedes #973
Related: https://github.com/BabylonJS/BabylonNative/issues/507, https://github.com/BabylonJS/BabylonReactNative/issues/215, and https://github.com/bkaradzic/bgfx/issues/2620
Testing:

Disable MSAA on Android/iOS

---

Dependencies/xr/Include/XR.h
Dependencies/xr/Source/OpenXR/XR.cpp
Plugins/NativeXr/Source/NativeXr.cpp

Rendering on OpenXR has been broken since [this change](https://github.com/BabylonJS/Babylon.js/pull/11042/files#diff-2a17806b7914d19ec3d0ae6759b133ae7d34f4b5f3a54e990a5f0eb697a17501R453) because OpenXR doesn't pre-clear textures handed to the application, whereas our ARCore and ARKit XR implementations do pre-clear the textures handed to the application by blitting the camera feed texture prior to app rendering.
fixes #933

Clear XR render target on OpenXR

---

Dependencies/xr/Source/OpenXR/XR.cpp
Dependencies/xr/Source/OpenXR/XrInput.cpp

There's an issue that shows up when tearing down the XR session with BabylonReactNative on windows where the input manager resources aren't disposed before the OpenXR context is reset.

Tear down XrInput before OpenXR context is reset

---

Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h

Added support for creating 2D texture arrays using the native engine. This allows morph targets to work properly. Also added length check to shader uniforms to avoid memory corruption when JS sends data with incorrect length to uniforms.

Fixed issue #923 by implementing 2D Texture Array to be used with Morph  targets.

---

Apps/Playground/macOS/ViewController.mm
Plugins/NativeInput/Include/Babylon/Plugins/NativeInput.h
Plugins/NativeInput/Source/Shared/NativeInput.cpp
Plugins/NativeInput/Source/Shared/NativeInput.h

This PR contains some changes to the NativeInput code to allow for negative values to be transmitted to the DeviceInputSystem.  Additionally, a function was tweaked for the MacOS input code to more accurately provide pointer coordinates.

DeviceInputSystem: Modify NativeInput to allow for negative integer values

---

Plugins/NativeXr/Source/NativeXr.cpp

fixes #997 
It was broken for every platforms. It didn't check the napi object could be unwrapped (exception) .

XRRay object Check

---

.github/workflows/master_update.yml
.github/workflows/nightly.yml
azure-pipelines.yml

Nightly was broken because `windows-latest` now defaults to this image : https://github.com/actions/virtual-environments/blob/win22/20220207.1/images/win/Windows2022-Readme.md
Which uses cmake 3.22.2 and VisualStudio 2022
Forcing to use 2019 until we decide to move to 2022 image and VS

CI running on Windows 2019 image

---

Plugins/NativeInput/Source/Shared/NativeInput.cpp

- Add missing new entries to calls to `GetOrCreateInputMap`
- Add back removed call to `RemoveInputMap`
- Add additional checks to filter out input state that is not buttons when determining whether to remove a touch device

Fix various regressions in NativeInput

---

Dependencies/xr/Source/ARKit/XR.mm

fixes #932 
excerpt from this documentation:
https://developer.apple.com/documentation/metal/mtlcommandbuffer/1442997-addcompletedhandler?language=objc
```
You can’t add a completion handler after you commit the command buffer.
```
So, adding it before `commit` fixes the issue. Tested with and **without** debugger.
Mostly a revert of revert ( https://github.com/BabylonJS/BabylonNative/pull/978 and https://github.com/BabylonJS/BabylonNative/pull/965)  and moved `addCompletedHandler`.

Fix iOS command queue completion handler

---

Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Context.cpp

fixes #996 
For some 2D shapes, stencil is needed. As it was used without a rendertarget supporting it, it brought a Metal validation error.
Adding a Depth/Stencil for Canvas.

Fix Metal Validation with Stencil in Canvas

---

Apps/Playground/Android/app/src/main/java/BabylonNative/BabylonView.java

In browsers, the canvas size is divided by the pixel density.
On my iPhone 11 with a pixel density of 2, the canvas size is 414x640 instead of native resolution.
On my Android, the density is 3. The surface area is 1/9 of native res.
In Native:
On iOS, the system (via `contentScaleFactor`) handles everything. 
On Android, the view size is returned in pixels, without taking care of pixel density. This PR adds its support.
The surfaceView bounds are not changed but the OpenGL area is resized with density factor. At presentation time, 
https://github.com/bkaradzic/bgfx/blob/3d4bd88c0635b614b453aac1003cc56a11d1ccf0/src/glcontext_egl.cpp#L375
Is taking care of setting the native window size so it gets rescaled by the compositor into the surfaceView.

Android Pixel Density

---

Plugins/NativeXr/Source/NativeXr.cpp

My BabylonJS PR here: https://github.com/BabylonJS/Babylon.js/pull/12097/files
Changed the contract for nativeXRFrame to require an implementation for getImageTrackingResults.  I thought this would not block Babylon.JS upgrade as we should only actually call getImageTrackingResults during image tracking, which is currently not supported, but the line in NativeXRFrame will run during XR startup. 
This PR just defines a dummy implementation for getImageTrackingResults to unblock XR startup, which should be effectively dead code at runtime since XRImageTrackingResult is not defined, so we should never allow initialization of WebXR Image Tracking

Dummy implementation for getImageTrackingResults

---

Dependencies/napi/napi-jsi/include/napi/napi-inl.h

Native Hermes APIs have differing behavior from from JSC and V8 where attempting to set an index value >= the length of the array will throw an unhandled exception.  This PR changes the napi-jsi implementation to account for this by manually extending the length of the array before calling setValueAtIndex.

Fix crash on hermes when calling Napi::Array::Set beyond length of array

---

Documentation/Readme.md

The Components link in Documentation/Readme.md doesn't point to anything. This change sets it to Components.md.

Fix Documentation/Readme.md link for Components

---

Core/Graphics/Include/RendererType/D3D11/Babylon/Graphics/RendererType.h
Core/Graphics/Include/RendererType/D3D12/Babylon/Graphics/RendererType.h
Core/Graphics/Include/RendererType/Metal/Babylon/Graphics/RendererType.h
Core/Graphics/Include/RendererType/OpenGL/Babylon/Graphics/RendererType.h
Core/Graphics/Include/Shared/Babylon/Graphics/Device.h
Core/Graphics/Source/DeviceImpl.cpp
Plugins/ExternalTexture/Include/Babylon/Plugins/ExternalTexture.h
Plugins/ExternalTexture/Source/ExternalTexture.cpp
Plugins/ExternalTexture/Source/ExternalTexture_D3D11.cpp
Plugins/ExternalTexture/Source/ExternalTexture_D3D12.cpp
Plugins/ExternalTexture/Source/ExternalTexture_Metal.cpp
Plugins/ExternalTexture/Source/ExternalTexture_OpenGL.cpp

Renaming `DeviceType` to `DeviceT` and `TextureType` to `TextureT` to avoid confusion with enums.

Rename DeviceType to DeviceT and TextureType to TextureT

---

Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Context.h

Changed class definition pattern for native context to avoid apparent leak in `Napi::DefineClass` on certain JavaScript engines. Pertains to https://github.com/BabylonJS/BabylonReactNative/issues/394.

Pattern change to work around memory leak

---

Apps/Playground/UWP/App.cpp

In our UWP code, there were some local variables used in the input functions to store address refs for some `ints`.  Since using the addresses adds no benefits but increases the complexity, this PR will remove those ampersand operators.  Originally, this was brought up by @ryantrem but the PR was merged before all instances of the operators on `ints` were removed.
This change has been tested and verified to work with both mouse and touch on UWP.

Removed & operator from local vars in UWP

---

Apps/Playground/UWP/App.cpp
Apps/Playground/Win32/App.cpp
Apps/Playground/macOS/ViewController.mm

An issue was recently found where the mouse wheel values were inverted for some platforms (as compared to Babylon.js).  After testing, it was found that Win32, UWP, and MacOS were using the incorrect values.  This PR contains changes to make these three platforms use the correct values.

NativeInput: Fix mouse wheel for MacOS and Windows

---

Apps/Playground/UWP/App.cpp
Apps/Playground/Win32/App.cpp
Apps/Playground/X11/App.cpp
Apps/Playground/macOS/ViewController.mm
Apps/ValidationTests/UWP/App.cpp
Apps/ValidationTests/Win32/App.cpp
Apps/ValidationTests/X11/App.cpp
Apps/ValidationTests/macOS/ViewController.mm
Core/Graphics/Include/Platform/Android/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/UWP/CoreWindow/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/UWP/SwapChainPanel/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/Unix/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/Win32/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/iOS/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/macOS/Babylon/Graphics/Platform.h
Core/Graphics/Include/Shared/Babylon/Graphics/Device.h
Core/Graphics/InternalInclude/Babylon/Graphics/BgfxCallback.h
Core/Graphics/Source/Device.cpp
Core/Graphics/Source/DeviceImpl.cpp
Core/Graphics/Source/DeviceImpl.h

Default is no MSAA unless set in the `WindowConfiguration` or updated later with `UpdateMSAA`.
Desktop playground and ValidationTests app MSAA set to 4.

MSAA parameter exposed to users

---

Core/Graphics/Source/DeviceImpl.cpp
Plugins/NativeEngine/Source/NativeEngine.cpp

- Update bgfx to include fixes for UWP
- Set max frame latency for bgfx init
- Use width and height from graphics instead of bgfx
#118

Fixes for resizing windows in UWP for D3D11

---

Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/VertexBuffer.cpp
Plugins/NativeEngine/Source/VertexBuffer.h

Issue reported by one partner when doing a ThinInstances buffer partial update.
byteOffset was not taken into account and buffer was forced to be the partial span.

Fix VertexBuffer update

---

Plugins/NativeCamera/Source/NativeVideo.cpp
Plugins/NativeCamera/Source/NativeVideo.h

[`HTMLMediaElement.play`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) is supposed to return a `Promise`, but our native implementation returns void. After this was implemented, Babylon.js [was later changed](https://github.com/BabylonJS/Babylon.js/commit/8969aaea7994b562f4c1f0f1e524994ffa1e0da5) to observe any errors (via `.catch`) on the promise returned from `play`. This means now that code dies trying to call `catch` on `undefined`. With this change, `play` now returns a completed promise. I think this is probably wrong because as far as I can tell, `play` is supposed to return a rejected promise with an error of type `NotAllowedError` if the user has not granted camera permissions. So I think there is more that needs to be done here to fully fix this, but …

Fix NativeCamera/VideoTexture by returning a promise from the play function

---

Plugins/NativeCamera/Source/Android/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/Android/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm

While adding the NativeCamera Plugin to Babylon React-Native I was hitting an issue where the plugin couldn't be initialized until after Graphics::DeviceContext had been initialized. The issue was that the plugin's constructor was saving off the current deviceContext reference to use later in the runtime. Because it was only using the deviceContext in one location I just removed it from the constructor and instead fetch it as needed later on when the plugin is used.

NativeCamera - Don't access Graphics::DeviceContext from the constructor

---

Dependencies/AndroidExtensions/Include/AndroidExtensions/JavaWrappers.h
Dependencies/AndroidExtensions/Source/JavaWrappers.cpp

While enabling the NativeCamera plugin in BabylonReactNative I started running into issues where the JNI layer was throwing exceptions due to calling methods with JNI jobject and jclass objects that had stale references on the JNI side. The issue was that the C++ layer holds onto the jclass and jobject references across boundary calls. That can lead to the Java side destroying the object while the C++ side still retains a reference to it.
The fix in this PR is to update the C++ side to create global references to the jobject and jclass references. That required adding getters/setters for managing registering and deregistering the global references from the Java side. Additionally I added copy and move semantic implementations to also ensure the jobject and jclass references are getting …

Manage Java JNI object lifetimes from the C++ side

---

Core/Graphics/Include/Platform/Android/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/UWP/CoreWindow/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/UWP/SwapChainPanel/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/Unix/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/Win32/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/iOS/Babylon/Graphics/Platform.h
Core/Graphics/Include/Platform/macOS/Babylon/Graphics/Platform.h
Core/Graphics/Include/Shared/Babylon/Graphics/Device.h
Core/Graphics/Source/Device.cpp
Core/Graphics/Source/DeviceImpl.cpp
Core/Graphics/Source/DeviceImpl.h

This change concerns mostly UWP/swapchainpanel but is also available for other platforms as bgfx allows it.
More infos on the rendering side here : https://github.com/bkaradzic/bgfx/pull/2837
- API contract mimics the MSAA one.
- bgfx update to the latest

Alpha premultiplied backbuffer

---

Apps/Playground/Android/app/src/main/cpp/BabylonNativeJNI.cpp
Plugins/NativeCamera/CMakeLists.txt
Plugins/NativeCamera/Source/Android/CameraWrappers.h
Plugins/NativeCamera/Source/Android/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/Android/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm
Plugins/NativeCamera/Source/NativeVideo.cpp
Plugins/NativeCamera/Source/NativeVideo.h
Plugins/NativeCamera/Source/UWP/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/UWP/NativeCameraImpl.h
Plugins/NativeCamera/Source/Unix/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/Unix/NativeCameraImpl.h
Plugins/NativeCamera/Source/Win32/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/Win32/NativeCameraImpl.h

This PR addresses a couple issues with the NativeCamera implementation. The first issue was that the `NativeCamera::Open` method returned a promise in an already completed state. For iOS this doesn't seem to be a problem. On Android it works so long as the permissions to use the camera were previously granted leading to the function executing synchronously. On Android if the permission prompt was showing the call to update the texture would be called while the Open method was still initializing leading to an error thrown trying to access the graphic context member variable. The fix was to have the `NativeCamera::Open` method return a promise in an uncompleted state and only complete it after the internal async work has finished.
The second issue this PR address was that the …

NativeCamera Fixes and Improvements

---

.github/jobs/android.yml
Apps/Playground/Android/app/build.gradle
Apps/ValidationTests/Android/app/build.gradle
azure-pipelines.yml

- Remove yesterday's hack (removing cmake 3.22.1 from Android toolchain)
- Set the CMake version to 3.19.6 instead of 3.19.0+
- set MacOS VM to latest instead of 10.15 so we will not realized 10.15 is removed when builds start failing
- Removed iOS 13 build
- Removed MacOS 10.15 build with xCode 12.4

Remove hack for cmake/android/ubuntu

---

Apps/Playground/Scripts/experience.js
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm

This PR improves resolution selection and orientation handling for Native Camera sessions on iOS.  As outlined in #1107 currently we are just taking the highest resolution setting on the camera ignoring the constraints set for maxWidth and maxHeight.   Additionally currently we are not making any adjustments to the outputted video texture for device orientation.  This PR fixes this so the output texture is oriented in a way that aligns with the screen.
Landscape before:
Landscape after:
Portrait before:
Portrait after:

Improve resolution selection and orientation handling for Native Camera on iOS

---

Apps/Playground/Scripts/experience.js
Plugins/NativeCamera/Include/Babylon/Plugins/NativeCamera.h
Plugins/NativeCamera/Source/Android/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/Android/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm
Plugins/NativeCamera/Source/NativeVideo.cpp
Plugins/NativeCamera/Source/NativeVideo.h
Plugins/NativeCamera/Source/UWP/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/UWP/NativeCameraImpl.h
Plugins/NativeCamera/Source/Unix/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/Unix/NativeCameraImpl.h
Plugins/NativeCamera/Source/Win32/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/Win32/NativeCameraImpl.h

This PR pushes the actual used camera dimension back to the NativeVideo texture so that readPixels and getSize return the proper dimensions of the object rather than defaulting to whatever is passed in for maxHeight and maxWidth as outlined in #1107.  With this change we will properly report the correct resolution on both iOS and Android.  Android requires additional follow up work to select the correct camera configuration to most closely match the target resolution.

Push camera dimensions back to NativeVideo texture

---

Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm

When setting up an AVCaptureSession we must manually set the session preset to AVCaptureSessionPresetInputPriority or else our selected format's resolution gets overwritten.  This PR properly sets that value prior to setting up the capture device so that our preferred resolution actually gets used.

Properly setup capture session to preserve selected format on iOS

---

Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm

Camera format resolutions are always in landscape. To the web implementation we need to swap height and width of the video format when reporting the size of the video texture when a session is started in portrait mode.

[iOS native camera] - Swap height and width camera dimensions & video texture size based on initial orientation

---

Apps/Playground/Scripts/experience.js
Dependencies/AndroidExtensions/Include/AndroidExtensions/JavaWrappers.h
Dependencies/AndroidExtensions/Source/JavaWrappers.cpp
Plugins/NativeCamera/Source/Android/NativeCameraImpl.cpp
Plugins/NativeCamera/Source/Android/NativeCameraImpl.h

This change addresses the android NativeCamera plugin implementation so that it picks a camera resolution based on the passed in maxWidth and maxHeight. Additionally this change fixes the rotation and orientation of the returned camera texture. More information about those two issues can be found in issue #1107.

Android native camera resolution and orientation

---

Plugins/ExternalTexture/Source/ExternalTexture_D3D11.cpp
Plugins/ExternalTexture/Source/ExternalTexture_D3D12.cpp
Plugins/ExternalTexture/Source/ExternalTexture_Metal.mm
Plugins/NativeEngine/Source/NativeEngine.cpp

This change makes it possible to use external textures with render target textures. It fixes setting the bgfx flag when constructing an external texture as well as make it such that creating a render target from an existing texture works in native engine.

Support external render target textures

---

Apps/Playground/Scripts/experience.js

With a previous change to improve the NativeCamera Plugin the default playground scene was modified in such a way that inputs were broken and the camera feature was enabled by default.
I've restored the previous camera instantiation and default to having the camera feature off. I then modified the setup for when the camera feature is on so it still functions as intended without interfering with when the feature is off.
I tested the changes on an Android device.

Fix playground scene input

---

Plugins/NativeCamera/CMakeLists.txt
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm

The BJS side creates the texture and specifies the format (as RGBA8, in NativeEngine.createDynamicTexture), and then the native side overrides the texture handle in the Graphics::Texture, but the other properties (including format) are not updated, so the format (BGRA8) is incorrect, and operations like readPixels won't work.
This change fixes the issue by using a shader to convert the camera's YpCbCr format into RGBA, similar to how it's done in [XR.mm](https://github.com/docEdub/BabylonNative/blob/97da91efb19cde88775a83fede8e5296ae234682/Dependencies/xr/Source/ARKit/XR.mm#L554-L636).
https://github.com/babylonjs/babylonnative/issues/1107

Fix iOS NativeCamera texture pixel format

---

Polyfills/Canvas/Source/Colors.h

When converting rgb and rgba strings to colors, browsers tolerate numbers out of the acceptable color range but BabylonNative does not.
This change updates the color string regex to accept negative numbers and clamps them to the acceptable color range of 0 to 255.
See https://forum.babylonjs.com/t/react-native-ssao-render-error/33489.
Related PR https://github.com/BabylonJS/Babylon.js/pull/12914.

Allow negative rgb and rgba values and clamp them to range 0-255

---

Dependencies/xr/Source/ARKit/XR.mm

In XR.mm when the call to `CVMetalTextureCacheCreateTextureFromImage` fails, the texture reference is not being released. In the Xcode AR example the texture reference is explicitly released when `CVMetalTextureCacheCreateTextureFromImage` fails, so we should probably do the same thing to make sure no memory is being leaked.

Fix potential memory leak on Apple platforms

---

Core/Graphics/Source/DeviceImpl.cpp
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm
Plugins/NativeCapture/Source/NativeCapture.cpp

This PR fixes a few issues related to the native camera implementation on iOS and readPixels
1. The current implementation for readTextureAsync assumes that the frame number will always increment by 1 when DeviceImpl::Frame is called.  This would be true if we only ever call bgfx::frame in DeviceImpl::Frame, but we have at least two other call sites for bgfx::frame, so this is not a true assumption.  In general this implementation was prone to the queue getting blocked, so I'm making it a bit more lenient.  (See #1131 for a related issue).
2. NativeCameraImpl was not creating a new ImplData object when calling reset() which meant that the unique pointer was invalid on subesquent NativeCamera open calls, and leading to an AV.
3. On Apple devices when initializing a video texture in …

Fix a few issues around readTexture and iOS camera

---

Plugins/NativeCamera/Source/Apple/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm

The current implementation of the cameraTextureDelegate was taking a strong reference to the implData object, which was preventing the destructor from being run on camera close.  This PR adds a small cleanup protocol to cleanly handle deallocation, and removes the circular reference.
Before:
After:

Fix iOS Camera Texture memory leak on dispose

---

Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm

This change makes it so that the NativeCamera plugin on iOS will use the devices main/primary camera for the VideoTexture. Previously it was picking the virtual (dual/triple) camera's first. The dual and triple cameras are a virtual camera that will swap between the different physical sensors on the device based on the zoom factor. Generally speaker they are the better camera to choose IF you are also in control of the zoom factor. That isn't currently the case for the Babylon implementation so it will be better to choose the main camera sensor instead of one of the virtual sensors.

NativeCamera - Use the main camera on iOS rather than virtual camera

---

Plugins/NativeCamera/Source/Apple/NativeCameraImpl.h
Plugins/NativeCamera/Source/Apple/NativeCameraImpl.mm
Plugins/NativeEngine/Source/NativeEngine.cpp

This PR fixes a few issues around NativeCamera start/stop synchronization.  
- The primary change is switching from using dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0) to using an arcana background scheduler for starting/stopping the AR camera session.  This is necessary as calls to  avCaptureSession stopRunning and avCaptureSession startRunning must be serialized or it will result in a crash at runtime.
- The second major change is changing CameraImpl to not be disposed on reset, but to instead handle managing its resources, and re-use durable resources across sessions.
- Removed unnecessary dispatch to the main thread in Open which could cause the camera to hang
- Texture creation promise will not resolve until the native camera session is actually ready
I …

iOS NativeCamera session start/stop synchronization

---

.github/workflows/nightly.yml
Apps/package.json
Apps/scripts/getNightly.js
Dependencies/UrlLib/Include/UrlLib/UrlLib.h
Dependencies/UrlLib/Source/Android/UrlRequest.cpp
Dependencies/UrlLib/Source/Apple/UrlRequest.mm
Dependencies/UrlLib/Source/Shared/UrlRequest.h
Dependencies/UrlLib/Source/Unix/UrlRequest.cpp
Dependencies/UrlLib/Source/Windows/UrlRequest.cpp
Polyfills/XMLHttpRequest/Source/XMLHttpRequest.cpp
Polyfills/XMLHttpRequest/Source/XMLHttpRequest.h

Fixing Nightly with these changes:
- Nightly bjs build download done with a node script instead of CI script (can be run locally)
- Fix syntax for objects created on the stack to be consistent with the rest of the code base
- add `getResponseHeader` and `getAllResponseHeaders` to XMLHttpRequest as it's now used in bjs
Note: impl added for Win32 and missing for Linux, Apple and Android.

XMLHttpRequest headers

---

Apps/UnitTests/Scripts/tests.js
Polyfills/Window/Source/TimeoutDispatcher.cpp

In rare cases it's possible for the timeout function's shared pointer to call delete from the `setTimeout` worker thread instead of the JavaScript runtime thread. This happens when the timeout function is dispatched in `CallFunction` and called on the runtime thread before the worker thread removes it from the time and id maps. In this case, it is destroyed on the worker thread when the timeout is removed from the id map since the runtime thread has already released its shared pointer reference to the function. This causes a Napi assert since the function object has to be destroyed on the same thread it was created on.
This change fixes the issue by holding a shared pointer to the timeout function while the timeout is being removed from the maps in the worker thread, and then moving that …

Fix `setTimeout` race condition

---

Dependencies/napi/napi-direct/source/js_native_api_javascriptcore.cc

This also separates external, reference, and wrapper objects so that the prototype chain is not ambiguous.
This fixes an issue where the app would assert and crash if the code persists a constructor.

Walk the prototype chain to find private data for NAPI/JSC

---

Plugins/NativeCamera/Source/Android/CameraDevice.cpp
Plugins/NativeCamera/Source/Apple/CameraDevice.mm
Plugins/NativeCamera/Source/CameraDeviceSharedPImpl.h
Plugins/NativeCamera/Source/MediaStream.cpp
Plugins/NativeCamera/Source/MediaStream.h
Plugins/NativeCamera/Source/NativeVideo.cpp
Plugins/NativeCamera/Source/UWP/CameraDevice.cpp
Plugins/NativeCamera/Source/Unix/CameraDevice.cpp
Plugins/NativeCamera/Source/Win32/CameraDevice.cpp

While testing the recent changes to the NativeCamera plugin I noticed that the camera stream was not consistently being closed after the VideoTexture (or even whole scene) was disposed. On iOS it was consistently closing, but took a few seconds. On Android it would only close the stream after opening a different babylon scene. After a bit more debugging I figured out the root issue has to do with garbage collection (possibly specifically in React-Native where I was testing).
This PR fulfills the [MediaStreamTrack stop() WebAPI](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/stop) so that the camera stream can be explicitly ended.
I've logged a related issue where Babylon.JS does not call stop() on the MediaStream tracks that it owns …

NativeCamera - Expose MediaStreamTrack stop() polyfill

---

Plugins/NativeCamera/Source/MediaStream.cpp
Plugins/NativeCamera/Source/UWP/CameraDevice.cpp
Plugins/NativeCamera/Source/Win32/CameraDevice.cpp

This PR is to resolve a compiler error I was getting when upgrading Babylon Native in Babylon React Native. The Windows compiler is pickier in that scenarios and treats the warning about unreachable code as an error.
The warning is fired because the CameraDevice class for Win32/UWP/Unix is a stub implementation that only throws errors instead of returning values. That leads to the compiler complaining on Windows that any code after a call to CameraDevice is unreachable (which is technically true).

NativeCamera - Disable unreachable code warning for non-supported platforms

---

Core/ScriptLoader/Include/Babylon/ScriptLoader.h
Core/ScriptLoader/Source/ScriptLoader.cpp

This is useful if the native side needs to do work on the JS thread after loading scripts.

Add dispatch function to ScriptLoader

---

Core/Graphics/Source/Texture.cpp

Follow up to #1173 to guard against calling Disown when texture is already not owned.

Add assert for Texture::Disown to guard against incorrect usage.

---

.github/jobs/linux.yml
azure-pipelines.yml

- Update Linux to use latest Clang/GCC compilers
- Use JavaScriptCore instead of V8 to work around #1190

Fix CI after Ubuntu updated from 20.04 to 22.04

---

BUILDING.md

1. Fixed the broken reference link to the 'All Development Platforms' section.
2. Emphasized creating a CMake 'build' directory to avoid weird ninja compilation as reported here in this [issue-1194](https://github.com/BabylonJS/BabylonNative/issues/1194).

Fixed broken URL link for 'All Development Platforms' section.

---

Plugins/NativeCamera/Source/Apple/CameraDevice.mm
Plugins/NativeCamera/Source/MediaDevices.cpp

This PR addresses two scenarios I observed where the NativeCamera implementation would crash on iOS.
The first was if the camera was created and then quickly destroyed. That would lead to an exception being thrown inside of the UpdateCameraTexture function due to the object being destroyed while the async task was still pending for BeforeRenderScheduler(). The fix for that scenario was to add an arcana cancelation source that gets cancelled when the stream is closed and the async task captures it as a shared reference so it persists after the parent object is destroyed.
The second crash happened during engine shutdown occasionally. The issue is that CameraDevice uses ARC to manage the lifetime of the textureRGBA member variable. It then passes that texture handler to …

NativeCamera - Fix iOS crash and expose enumerateDevices

---

Plugins/NativeCamera/Source/Android/CameraDevice.cpp
Plugins/NativeCamera/Source/Apple/CameraDevice.mm
Plugins/NativeCamera/Source/CameraDevice.h
Plugins/NativeCamera/Source/MediaStream.cpp
Plugins/NativeCamera/Source/MediaStream.h
Plugins/NativeCamera/Source/NativeVideo.cpp
Plugins/NativeCamera/Source/NativeVideo.h
Plugins/NativeCamera/Source/UWP/CameraDevice.cpp
Plugins/NativeCamera/Source/Unix/CameraDevice.cpp
Plugins/NativeCamera/Source/Win32/CameraDevice.cpp

This PR updates the implementation of the NativeCamera plugin to support the HTMLVideoElement resize event. See [this doc](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoHeight#examples) for an example of how the web API works.
The main scenario where the video dimensions would change for the NativeCamera is when the device orientation changes. This issue is mentioned in more detail in issue #1107 
Exposing the resize event will allow the Babylon.JS VideoTexture to respond to the underlying video size changes and update the internal texture accordingly. This enables rotating the device while maintaining the same VideoTexture object and maintaining the same NativeCamera in conjunction with it. This becomes more important if you use the move advanced camera …

NativeCamera - Add support for HTMLVideoElement resize event polyfill

---

Apps/Playground/Scripts/experience.js
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h

This code allows making shader compilation occur in a separate thread so that it doesn't block the Javascript thread. It's intended to be reverse-compatible with BabylonJS as of commit [52d30c49fffd2d9bd446668eb0b61337f7c167aa](https://github.com/BabylonJS/Babylon.js/commit/52d30c49fffd2d9bd446668eb0b61337f7c167aa) on master, but shaders will not compile asynchronously with that version; I will make another PR into BabylonJS with the necessary Typescript code to support asynchronous shader compilation using this code, and the shader compilation will be asynchronous only when both updates are used together.
Fixes #402
The PR for the BabylonJS side has now been opened:
https://github.com/BabylonJS/Babylon.js/pull/13587

Asynchronous shader compilation

---

Apps/Playground/Android/app/build.gradle
Plugins/NativeCamera/Source/Android/CameraWrappers.h

Same NDK version as React-Native 0.71
fixes https://github.com/BabylonJS/BabylonReactNative/issues/566

Bump NDK and disable compilation error in Android Camera

---

.clang-format
Core/Graphics/Source/DeviceImpl.cpp
Plugins/NativeCamera/Source/Android/CameraDevice.cpp
Plugins/NativeCamera/Source/Android/CameraWrappers.h
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h
Plugins/NativeInput/Source/Shared/DeviceInputSystem.cpp
Plugins/NativeInput/Source/Shared/NativeInput.cpp
Plugins/NativeXr/Source/NativeXr.cpp
Plugins/TestUtils/Source/Unix/TestUtilsImpl.cpp
Plugins/TestUtils/Source/Win32/TestUtilsImpl.cpp

The previous [PR](https://github.com/BabylonJS/BabylonNative/pull/1201) assumed clang-format version 11. VS2022 uses version 15. This change will make the formatting compatible with VS.

Make clang-format compatible with VS

---

Polyfills/Canvas/Source/Context.cpp

A quick fix for Canvas Context clip function. Width and Height were wrongly assigned when doing clipping.

Quick fix for CanvasContext Clip function

---

.github/jobs/win32.yml
Plugins/TestUtils/Source/TestUtils.cpp

The `TestUtils::WritePNG` function silently fails if the given .png file's directory does not exist. This change creates the directory if it does not exist, yet, so opening the .png for write succeeds.

Make .png output directory if it doesn't exist

---

Apps/Playground/Scripts/experience.js

This is basically a test PR :)
Changed wireframe section to display material's wireframe instead of point cloud. I believe it can only be one or the other, as far as `material.wireframe` and `material.pointcloud` go.
Also changed loop to use `index` instead of `0`.

Fix experience.js typo

---

Plugins/ExternalTexture/Source/ExternalTexture_Base.h
Plugins/ExternalTexture/Source/ExternalTexture_D3D11.cpp
Plugins/ExternalTexture/Source/ExternalTexture_D3D12.cpp
Plugins/ExternalTexture/Source/ExternalTexture_Metal.mm
Plugins/NativeEngine/Source/NativeEngine.cpp

This is the native counter part to https://github.com/BabylonJS/Babylon.js/pull/14055.

Basic support of MSAA for render targets

---

.github/jobs/win32.yml
Install/Test/CMakeLists.txt
Install/Test/nuget.config
Install/Test/packages.config

Build the UnitTests app using installation lib/headers. If the build fails, something is missing in the installation process.
Some questions:
- Do we want to have Debug/Release testing?
- PDBs?
- Do we want to package the installation and test that package instead (npm? nuget?)
- Do we want to package for another platform ?
- Do we want to test the unittest build in this process instead ?

Win32 Installation test

---

Apps/package-lock.json
Apps/package.json
Plugins/NativeEngine/Source/NativeEngine.cpp

Brings in changes from https://github.com/BabylonJS/Babylon.js/pull/14292 as part of the package version update.
The main fix was a misunderstanding of the `BGFX_TEXTURE_MSAA_SAMPLE` flag in bgfx and how textures are resolved. Thanks to @sebavan for explaining to me how texture resolving works.

Fix MSAA when using rendering pipelines

---

CMakeLists.txt

Sets fetched URL contents to the time of extraction, not the timestamps in the archive.
This is to prevent the CMake warning occurring due to the recently merged changes that fetch the googletest dependency as a .tar.gz URL.

Set CMake policy CMP0135 to NEW

---

Apps/Playground/UWP/App.cpp
Apps/Playground/Win32/App.cpp
Apps/Playground/iOS/LibNativeBridge.h
Apps/Playground/iOS/LibNativeBridge.mm
Apps/Playground/iOS/ViewController.swift
Apps/Playground/macOS/ViewController.mm

The BabylonNative playground app pick points are inaccurate on Win32, UWP, macOS and iOS.
This change fixes the issues and also adds mouse-move tracking on macOS.
Fixes https://github.com/BabylonJS/BabylonNative/issues/1291.
Tested on playground https://playground.babylonjs.com/#VXUJZA.
Tested for regressions per suggestions from @PolygonalSun on:
- Default playground for FreeCamera.
- https://playground.babylonjs.com/#SRZRWV#839 for ArcRotateCamera.
- https://playground.babylonjs.com/#H5PZ4Q for picking.
- https://playground.babylonjs.com/#SG9ZZB for gizmos.

Fix playground pointer position

---

Apps/package-lock.json
Apps/package.json

This PR will update the version of Babylon.js used to 6.21.2.  The purpose for this is to address the following bugs:
- https://github.com/BabylonJS/BabylonNative/issues/1222
- https://github.com/BabylonJS/BabylonNative/issues/1223

Update Babylon.js to 6.21.2

---

CMakeLists.txt

This brings in a small change that prevents an object copy due to a situation that prevents RVO (more details in the JsRuntimeHost PR for the commit): https://github.com/BabylonJS/JsRuntimeHost/commit/b3d4f2cb8c86fb55dc4e8ae78ba5f5a98a5be6ba

Update to latest JsRuntimeHost

---

Apps/Playground/Android/gradle.properties
BUILDING.md
CMakeLists.txt
Dependencies/xr/Source/ARCore/XR.cpp

This code has been in the Android XR implementation forever, and was never understood. It did an explicit eglSwapBuffers to present to the screen, which was needed in Babylon React Native as somehow the bgfx rendering path was different between the two. Now, even in BRN this results in double rendering. Maybe this is a result of one of the bgfx updates. Since it seems to no longer be needed in any scenario, this PR removes it. Unfortunately XR on Android in the BN Playground is broken in a different way currently, so I have not been able to verify this works correctly in that scenario. But previously this code was incorrect in BN anyway, so I expect this is correct now in both BN and BRN.

Remove Android xr double render

---

Apps/CMakeLists.txt
Apps/UnitTests/Android/app/src/main/cpp/CMakeLists.txt
CMakeLists.txt

- Enable apps and install targets only when project is top level
- Only include GoogleTest dependency when necessary
- Put GoogleTest targets in dependencies folder
- Bring in new CMakeExtensions with better npm helper function

Miscellaneous build fixes

---

Plugins/NativeCamera/Source/ImageCapture.cpp

BRN build fails on CI because of unreachable code in ImageCapture.cpp
```
D:\...\submodules\BabylonNative\Plugins\NativeCamera\Source\ImageCapture.cpp(155): warning C4702: unreachable code 
D:\...\submodules\BabylonNative\Plugins\NativeCamera\Source\ImageCapture.cpp(187): warning C4702: unreachable code 
```
I do not see what can cause this warning. Moreover, it only concerns x86 Release. As I have no clue on how to fix it, I disable the warning.

Disable unreachable code warning

---

Plugins/ExternalTexture/Source/ExternalTexture_Base.h
Plugins/ExternalTexture/Source/ExternalTexture_D3D11.cpp
Plugins/ExternalTexture/Source/ExternalTexture_D3D12.cpp
Plugins/ExternalTexture/Source/ExternalTexture_Metal.mm
Plugins/ExternalTexture/Source/ExternalTexture_Shared.h

- Change `GetInfo` to static to avoid accidentally using class members
- Change `Update` function to only compare width and height and add missing assignment of `m_info` and `UpdateHandles` call

External texture fixes for Apple

---

Apps/Playground/Android/app/build.gradle
Apps/UnitTests/Android/app/build.gradle
CMakeLists.txt

follow up https://forum.babylonjs.com/t/build-failed-on-windows-for-android-apk/45026/7
npm install was not called on Android because `PROJECT_IS_TOP_LEVEL` is false is Apps cmake is only evaluated when true.
Fixed by forcing Apps folder evaluation on Android.

fix npm install for android app

---

CMakeLists.txt

This resolves an issue with building for iOS Simulator on Apple Silicon.

Update ios-cmake to 4.4.1

---

Apps/Playground/macOS/ViewController.mm

Fixed validation tests in MacOS. Playground was not properly configured to run validation tests when running in MacOS.

Fixed validation tests in MacOS

---

CMakeLists.txt

Changed glslang to point to the repo that is hosted by Babylon. This repo has GLSLANG_WEB_MIN flag working for all platforms.

Updated glslang to enable GLSLANG_WEB_MIN

---

Apps/UnitTests/Shared/Tests.h
Core/Graphics/InternalInclude/Babylon/Graphics/DeviceContext.h
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h
Plugins/TestUtils/Source/TestUtils.cpp
Plugins/TestUtils/Source/TestUtils.h
Polyfills/Canvas/Source/Image.cpp
Polyfills/Canvas/Source/Image.h
Polyfills/Canvas/Source/nanovg_babylon.cpp

When shutting down the engine while having some textures, it's possible for NativeEngine to be disposed before the textures.
In this lambda:
https://github.com/BabylonJS/BabylonNative/blob/95240a59f2e1483d4c4b92b329b84ff333f0de84/Plugins/NativeEngine/Source/NativeEngine.cpp#L216
The imageContainer has still a ref to NativeEngine::m_allocator that gets invalid
https://github.com/bkaradzic/bimg/blob/5d61905eb1aa8074ee62553b4a7bd2dc16f4cf24/src/image.cpp#L3335
Setting m_allocator as static fixes the issue. It only contains a vtable so it's threadsafe.

Static engine allocator

---

CMakeLists.txt
Core/Graphics/CMakeLists.txt
Core/Graphics/Source/DeviceImpl.cpp

In some integrations the application might want to call graphics call from multiple threads. This PR adds the possibility of making thread affinity checks configurable by CMake.

Changed thread affinity checks to be optional

---

Core/Graphics/Source/DeviceImpl.cpp
Core/Graphics/Source/DeviceImpl.h
Core/Graphics/Source/DeviceImpl_Android.cpp
Core/Graphics/Source/DeviceImpl_Unix.cpp
Core/Graphics/Source/DeviceImpl_Win32.cpp
Core/Graphics/Source/DeviceImpl_WinRT.cpp
Core/Graphics/Source/DeviceImpl_iOS.mm
Core/Graphics/Source/DeviceImpl_macOS.mm

bgfx default is to do page flip before rendering a new frame. So, rendering 1 frame is not enough to see rendering on screen.
This 1 frame latency was visible on Apple and fixed with this PR:
https://github.com/BabylonJS/BabylonNative/pull/525
Unfortunately, the issue has been reported on Windows as well. With this PR, flipping will always be after rendering.
Related posts: 
https://github.com/bkaradzic/bgfx/issues/339

flipping happens after rendering

---

CMakeLists.txt
Dependencies/xr/Source/ARCore/XR.cpp

This fixes two regressions:
1. XHR in BRN (see https://github.com/BabylonJS/JsRuntimeHost/pull/71)
2. XR on Android (see the comment)

Fix XHR and XR regressions

---

Apps/Playground/Android/app/build.gradle
Apps/Playground/Android/build.gradle
CMakeLists.txt
Dependencies/xr/Source/ARCore/XR.cpp

On some Android devices, XR in the BRN Playground flickers. It turns out this is because:
1. On some (or all?) devices, if eglMakeCurrent is called with an egl surface that was created with a different egl config than a surface previously made current in the given context, it will fail.
2. In xr.cpp, we manually construct an egl config for the XR surface.
3. When we setup the attributes used to choose an egl config, we do not specify an msaa attribute (we ignore msaa).
4. The BRN Playground sets msaa to 2.
5. BGFX chooses an egl config with the msaa=2 attribute.
6. xr.cpp chooses a different config.
7. The eglMakeCurrent call fails.
8. The OpenGLHelpers MakeCurrent function ignores error codes from eglMakeCurrent.
9. That silent failure leads to xr rendering to the same surface as the …

Reuse current surface config

---

.github/jobs/win32.yml
CMakeLists.txt

See #1351. This a stopgap solution. Proper implementation needs to happen after https://github.com/BabylonJS/JsRuntimeHost/pull/73 is merged.

Update JsRuntimeHost to pick up napi_add_finalizer for JSC

---

Apps/Playground/Scripts/experience.js
Apps/Playground/iOS/Info.plist
Plugins/NativeCamera/Source/Apple/CameraDevice.mm
Plugins/NativeCamera/Source/ImageCapture.cpp
Plugins/NativeEngine/Source/NativeEngine.cpp

`ImageCapture` was implemented for iOS a while back, but had a few outstanding bugs that are addressed in this PR:
1. Flash modes were not working - there were actually two bugs here, the first being that we were trying to get supported flash modes from the `AVPhotoCaptureOutput` before we actually created the `AVPhotoCaptureOutput` (oops), and second there was a missing line to increment the current index when populating the flash modes array.
2. There was no code to deal with image rotation, so the created image was always sideways (I believe based on the orientation of the physical camera sensor relative to the orientation of the device).
So the changes here are to fix the issues of bullet 1 and add code for bullet 2.
I also made some small changes to experience.js to reflect the …

Fix flash and image orientation for iOS image capture

---

Core/Graphics/Include/Shared/Babylon/Graphics/Device.h
Core/Graphics/InternalInclude/Babylon/Graphics/DeviceContext.h
Core/Graphics/InternalInclude/Babylon/Graphics/FrameBuffer.h
Core/Graphics/InternalInclude/Babylon/Graphics/Texture.h
Core/Graphics/Source/Device.cpp
Core/Graphics/Source/DeviceContext.cpp
Core/Graphics/Source/DeviceImpl.cpp
Core/Graphics/Source/DeviceImpl.h
Core/Graphics/Source/FrameBuffer.cpp
Core/Graphics/Source/Texture.cpp
Plugins/ExternalTexture/Source/ExternalTexture_Shared.h
Plugins/NativeEngine/Source/IndexBuffer.cpp
Plugins/NativeEngine/Source/IndexBuffer.h
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h
Plugins/NativeEngine/Source/VertexArray.cpp
Plugins/NativeEngine/Source/VertexArray.h
Plugins/NativeEngine/Source/VertexBuffer.cpp
Plugins/NativeEngine/Source/VertexBuffer.h
Polyfills/Canvas/Source/Canvas.cpp

This PR implements changes to Babylon Native that allow it to properly handle graphics device loss scenarios. When the graphics device currently been used by Babylon Native gets invalidated the correct workflow will be to call ```Babylon::Graphics::Device::DisableRendering``` recreate the graphics device infrastructure, use the new API ```Babylon::Graphics::Device::UpdateDevice``` to  give the new device to Babylon Native and than call ```Babylon::Graphics::Device::EnableRendering``` to start bgfx again with a new device. 
This also requires Babylon.js to be notified that the current device context was lost and re-created. This can be done by calling:
```
engine._contextWasLost = true;
engine._restoreEngineAfterContextLost(() => { });
``` 
This will force Babylon.js to recreate all …

Allow device loss handle

---

CMakeLists.txt
Install/Install.cmake
Plugins/NativeCamera/Include/Babylon/Plugins/NativeCamera.h
Plugins/NativeCamera/Source/NativeCamera.cpp
Plugins/NativeCapture/Include/Babylon/Plugins/NativeCapture.h
Plugins/NativeCapture/Source/NativeCapture.cpp
Plugins/NativeEngine/Include/Babylon/Plugins/NativeEngine.h
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeInput/Include/Babylon/Plugins/NativeInput.h
Plugins/NativeInput/Source/Shared/NativeInput.cpp
Plugins/NativeOptimizations/Include/Babylon/Plugins/NativeOptimizations.h
Plugins/NativeOptimizations/Source/NativeOptimizations.cpp
Plugins/NativeTracing/Include/Babylon/Plugins/NativeTracing.h
Plugins/NativeTracing/Source/NativeTracing.cpp
Plugins/NativeXr/Include/Babylon/Plugins/NativeXr.h
Plugins/NativeXr/Source/NativeXr.cpp
Plugins/TestUtils/Include/Babylon/Plugins/TestUtils.h
Plugins/TestUtils/Source/Win32/TestUtilsImpl.cpp
Plugins/TestUtils/Source/WinRT/TestUtilsImpl.cpp
Polyfills/Canvas/Include/Babylon/Polyfills/Canvas.h
Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Window/Include/Babylon/Polyfills/Window.h
Polyfills/Window/Source/Window.cpp

Without explicit calling convention modifers, consumers are required to compile with the same calling convention used in the released binaries. If a consumer compiles with the `__stdcall` calling convention, the linker won't resolve the function calls because the released binaries are built with the default `__cdecl` calling convention.
This change fixes the issue using an overridable `BABYLON_API` macro defined as `__cdecl` by default on Windows platforms or defined as empty on non-Windows platforms.
See also https://github.com/BabylonJS/JsRuntimeHost/pull/86.

Use new JsRuntimeHost `BABYLON_API` calling convention macro

---

.github/jobs/ios.yml
.github/jobs/macos.yml
Apps/Playground/Android/app/CMakeLists.txt
Apps/Playground/Android/app/build.gradle
CMakeLists.txt
Polyfills/Canvas/Source/nanovg_babylon.cpp
azure-pipelines.yml

See https://forum.babylonjs.com/t/pixel-8-pro-crash/48956. Specifically, the fix that makes the code work is https://github.com/bkaradzic/bgfx/pull/3187.
This change also:
- Cleans up the Android build such that the build output goes to the `Build/Android` folder.
- Update CI to latest Xcode since the old compilers no longer compile with latest bgfx.

Update to latest bgfx.cmake

---

Core/Graphics/InternalInclude/Babylon/Graphics/FrameBuffer.h
Core/Graphics/InternalInclude/Babylon/Graphics/Texture.h
Core/Graphics/Source/Texture.cpp
Plugins/NativeEngine/Source/NativeEngine.cpp

The changes in https://github.com/BabylonJS/Babylon.js/pull/15052 exposes a problem in native where the output texture of the BRDF post process will be destroyed causing a crash in bgfx.
In the previous code, the `NativeEngine::CreateFrameBuffer` took ownership of the color texture passed in as an argument. This is wrong because the texture might still be needed after the frame buffer dies. Specifically, [the BRDF post process that expands the RGBD env texture](https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Misc/rgbdTextureTools.ts#L98) is where it fails.
The new code will not take ownership of the color texture but will still delete the generated depth/stencil texture in the finalizer if necessary. The calling code will destroy the color texture when …

Fix ownership of color texture when creating a frame buffer

---

Apps/Playground/iOS/ViewController.swift

Fix bug introduced with https://github.com/BabylonJS/BabylonNative/pull/1368 
xrView.isHidden was not the intended value.
I've kept the syntax proposed by @okwasniewski
idk if it's the 'correct' and standard way to do it.
cc @Allan121
fixes #1379

fix xrView visibility iOS

---

CMakeLists.txt
Plugins/NativeEngine/Source/NativeEngine.cpp

follow up https://forum.babylonjs.com/t/post-processing-graphics-glitch/49523/35
tldr: glitches with Arm Mali GPU and 32b depth buffer.
fix: replace D32 with D24S8
fixes #1381

Android D24S8 for depthbuffer

---

Apps/Playground/Scripts/validation_native.js
Apps/package-lock.json
Apps/package.json

Due to https://github.com/BabylonJS/Babylon.js/pull/15217, we have to call `engine.releaseEffects` before every test to make sure it starts fresh.

Update to Babylon.js 7.12.0

---

Documentation/ComsumingJavascript.md
README.md

Added a little documentation on how to consume JavaScript files in a Babylon Native application, as well as some warnings about using es6 bundles from Babylon.JS 7.19.0 or higher due to the usage of dynamic import.

Added documentation about ES6 bundles and Babylon Native

---

Core/Graphics/Include/RendererType/D3D11/Babylon/Graphics/RendererType.h
Core/Graphics/Include/RendererType/D3D12/Babylon/Graphics/RendererType.h
Core/Graphics/Include/RendererType/Metal/Babylon/Graphics/RendererType.h
Core/Graphics/Include/RendererType/OpenGL/Babylon/Graphics/RendererType.h
Install/Install.cmake
Plugins/ExternalTexture/Include/Babylon/Plugins/ExternalTexture.h
Plugins/ExternalTexture/Source/ExternalTexture_D3D11.cpp
Plugins/ExternalTexture/Source/ExternalTexture_D3D12.cpp
Plugins/ExternalTexture/Source/ExternalTexture_Metal.mm
Plugins/ExternalTexture/Source/ExternalTexture_OpenGL.cpp
Plugins/ExternalTexture/Source/ExternalTexture_Shared.h

In D3D, some textures have multiple planes (e.g., NV12). In order to access these planes, the format for the D3D shader resource view must be different than the format of the texture. See NV12 section of the [DXGI_FORMAT doc](https://learn.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format). This change makes it possible to override the texture format to something different than the one from the texture itself when creating the external texture.

Add ability to override texture format in ExternalTexture

---

Plugins/ExternalTexture/Readme.md

Added documentation on how do use ExternalTexture to get pixel data from the Babylon.js renderer.

Updated external texture documentation

---

BUILDING.md
CMakeLists.txt

And add a troubleshooting section to iOS build instructions.

Pull in latest JSRuntimeHost with JSC reference management fixes

---

Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Context.h

- Adds bindings for setting and getting `letterSpacing` https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/letterSpacing
- Adds implementation for setter and getter

Add letterSpacing polyfill and implementation

---

Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Context.h
Polyfills/Canvas/Source/Path2D.cpp
Polyfills/Canvas/Source/Path2D.h

- https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getTransform
- https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform
- https://developer.mozilla.org/en-US/docs/Web/API/Path2D/addPath#transform
usage:
```
// Path 2D
let path = new _native.Path2D();
let path2 = new _native.Path2D("M 10,30 A 20, 20 0, 0, 1 50, 30 A 20, 20 0, 0, 1 90, 30 Q 90, 60 50, 90 Q 10, 60 10, 30 z");
path.addPath(path2, { a: 1, b: 0, c: 0, d: 1, e: 400, f: 0 }); // shift right 400
context.stroke(path);
```

Canvas Transforms:  getTransform setTransform, addPath (Path2D)

---

.github/jobs/test_install_linux.yml
Apps/Playground/Scripts/experience.js
Apps/package-lock.json
Apps/package.json
Install/Install.cmake
Install/Test/CMakeLists.txt
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Context.h
Polyfills/Canvas/Source/Path2D.cpp

- Adds example Path2D usage in experience.js.
- Makes Path2D work with .fill as well

canvas fill Path2D

---

Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Canvas.h
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Path2D.cpp

- Supports passing Path2D to Path2D constructor
- Handles >1 args for context.fill
- As [matanui159](https://github.com/BabylonJS/BabylonNative/issues?q=is%3Apr%20is%3Aopen%20author%3Amatanui159), as pointed out, `SetHeight`, `SetWidth` clears canvas on browser even if width/height doesn't change. We re-use framebuffer but clear it in this scenario.

fixes: canvas.SetHeight/Width, Path2D, context.fill

---

Polyfills/Canvas/CMakeLists.txt
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Context.h
Polyfills/Canvas/Source/Font.cpp
Polyfills/Canvas/Source/Font.h

This improves the handling of the "font" field on the context to properly parse out weight/style/size. Currently weight and style are unused since the font map only takes the family name into consideration.

Improve parsing of the "font" field

---

Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/FrameBufferPool.cpp
Polyfills/Canvas/Source/nanovg/nanovg_babylon.cpp

Fixes:
- Depth stencil missing. Not optional in nanovg
- Unnecessary texture creation. This was caused by a bad merge resolution ([link](https://github.com/BabylonJS/BabylonNative/pull/1489/commits/50697ff3e4937cf8a2932fc67d95b5b7eddf9684))
- Missing `m_available` increment when framebuffer released caused infinite framebuffer creation
The various warnings about missing stencil bugger and failed to allocate framebuffer are now gone.

fix: pool framebuffer stencil, release issues

---

Apps/Playground/Scripts/experience.js
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Path2D.cpp
Polyfills/Canvas/Source/Path2D.h

MDN: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect
Implements CSS-style radius array argument

Canvas Path2D roundRect

---

Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Context.h

MDN: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/direction
MDN: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getTransform
- Context direction is incomplete. Further investigation is needed on a solution to deal with ligatures (eg. stb_freetype + harfbuzz?)
- Context getTransform() now returns missing DOMMatrix properties

Canvas direction + getTransform() fix

---

Apps/package-lock.json
Apps/package.json
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h
Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Canvas.h
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Context.h

BJS PR ( ~~https://github.com/BabylonJS/Babylon.js/pull/16497~~ https://github.com/BabylonJS/Babylon.js/pull/16502 )needs to be merged before and a new NPM needs to be generated. 
Copy texture is now a queued command (see BJS PR), protocol changed.
Before: 
- canvas rendering was done with a task, in sync with frame rendering. 
Now:
- canvas rendering is done when when copying texture. Browser HTML Canvas rendering happens when rendering commands are issued. With Native, nanovg keeps its own queue that needs to be actually done before the copy. This is done with the `flush` command.
- Because of this 'flush when needed', no need to keep a dirty flag in the context.
- In order to always get the same context with `Canvas.getContext` some code from `CanvasTest` branch has been integrated in …

CopyTexture command

---

.github/jobs/linux.yml
Apps/package-lock.json
Apps/package.json
CMakeLists.txt
Plugins/NativeCamera/Source/MediaDevices.cpp
Plugins/NativeCamera/Source/MediaStream.cpp
Plugins/NativeEngine/Source/NativeEngine.cpp
Plugins/NativeEngine/Source/NativeEngine.h
Plugins/NativeXr/Source/XRFrame.cpp
Plugins/NativeXr/Source/XRHitTestResult.h
Plugins/NativeXr/Source/XRPlane.h
Plugins/NativeXr/Source/XRSession.cpp
Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Canvas.h
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Context.h
azure-pipelines.yml

This brings in the changes from master to fix timing/sequencing issues related to copyTexture and deleteTexture.
This included changes on the JS side, so it brings with it new versions of the BJS packages.

Merge copy texture fix

---

Apps/Playground/Scripts/experience.js
Polyfills/Canvas/Source/Context.cpp
Polyfills/Canvas/Source/Path2D.cpp
Polyfills/Canvas/Source/Path2D.h
Polyfills/Canvas/Source/nanovg/nanovg.cpp
Polyfills/Canvas/Source/nanovg/nanovg.h

MDN: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect
Adds support for single DOMPoint argument in roundRect (Context, Path2D)
Looks like `nvgRoundedRectVarying` already implemented seperate x/y radius, so just needed to add extra args

Canvas roundRect DOMPoint argument

---

Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Context.cpp

@ryantrem found that when we load in a replacement font buffer..
the old buffer passed to nvgCreateFontMem is freed and can get corrupted
To solve this, we've made LoadTTFAsync effectively synchronous and don't allow loading in a duplicate font. We can consider future work to support safely updating existing fonts

fix: don't allow loading same font more than once

---

Polyfills/Canvas/Source/Canvas.cpp
Polyfills/Canvas/Source/Canvas.h

small followup to https://github.com/BabylonJS/BabylonNative/pull/1516

Canvas synchronous LoadTTF

---

CMakeLists.txt

CMake 4 issues an error when the cmake minimum required version is less than 3.5, and a warning when less than 3.10.
This change updates spirv-cross to bump its cmake minimum version to resolve the error.

Fix CMake 4 errors

---

Apps/babel.config.json

Set babel "compact" option to `false` to silence warning on large mocha.js file.
See https://babeljs.io/docs/options#compact. Leaving this option set to the "auto" default causes a warning for mocha.js since it is > 500kb.

Silence babel warning on large mocha.js file

---

Plugins/NativeEngine/Source/ShaderCompilerMetal.cpp

When we do string replacement for metal shaders we might replace the wrong substring if the original sampler name had "Texture" in the name. This is the reason why shadows currently don't work when using metal.

Fixed string replacement in metal shaders

---

.github/jobs/test_install_win32.yml
.github/jobs/uwp.yml
.github/jobs/win32.yml
Core/Graphics/InternalInclude/Babylon/Graphics/FrameBuffer.h
Core/Graphics/Source/DeviceImpl.h
Core/Graphics/Source/FrameBuffer.cpp
Plugins/NativeEngine/Source/NativeEngine.cpp
nightly.yml

- [JS thread] engine is disposed from 
- [main thread] resetView is called 
- [main thread] DisableRendering -> bgfx context is destroyed
- [JS thread] ExternalWithFinalizer for the `depthStencilTextureHandle`

FrameBuffer depthStencil texture destruction fix
